import { HeadOfStateNoId } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Argentina`;

const countryId = 20;

export const argentina: HeadOfStateNoId[] = [
	{
		countryId,
		name: `Bartolomé Mitre`,
		tookOffice: new Date(`12 December 1861`),
		leftOffice: new Date(`12 October 1868`),
		party: `Liberal`,
		leaning: 0,
	},
	{
		countryId,
		name: `Domingo Faustino Sarmiento`,
		tookOffice: new Date(`12 October 1868`),
		leftOffice: new Date(`12 October 1874`),
		party: ``,
		leaning: 0,
	},
	{
		countryId,
		name: `Nicolás Avellaneda`,
		tookOffice: new Date(`12 October 1874`),
		leftOffice: new Date(`12 October 1880`),
		party: `National Autonomist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Alejo Julio Argentino Roca`,
		tookOffice: new Date(`12 October 1880`),
		leftOffice: new Date(`12 October 1886`),
		party: `National Autonomist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Miguel Ángel Juárez Celman`,
		tookOffice: new Date(`12 October 1886`),
		leftOffice: new Date(`6 August 1890`),
		party: `National Autonomist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Pellegrini`,
		tookOffice: new Date(`6 August 1890`),
		leftOffice: new Date(`12 October 1892`),
		party: `National Autonomist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Luis Sáenz Peña`,
		tookOffice: new Date(`12 October 1892`),
		leftOffice: new Date(`22 January 1895`),
		party: `National Autonomist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Evaristo Uriburu`,
		tookOffice: new Date(`22 January 1895`),
		leftOffice: new Date(`12 October 1898`),
		party: `National Autonomist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Julio Argentino Roca`,
		tookOffice: new Date(`12 October 1898`),
		leftOffice: new Date(`12 October 1904`),
		party: `National Autonomist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Manuel Quintana`,
		tookOffice: new Date(`12 October 1904`),
		leftOffice: new Date(`12 March 1906`),
		party: `National Autonomist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Figueroa Alcorta`,
		tookOffice: new Date(`12 March 1906`),
		leftOffice: new Date(`12 October 1910`),
		party: `National Autonomist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Roque Sáenz Peña`,
		tookOffice: new Date(`12 October 1910`),
		leftOffice: new Date(`9 August 1914`),
		party: `National Autonomist Party (Modernist)`,
		leaning: 0,
	},
	{
		countryId,
		name: `Victorino de la Plaza`,
		tookOffice: new Date(`9 August 1914`),
		leftOffice: new Date(`12 October 1916`),
		party: `National Autonomist Party (Modernist)`,
		leaning: 0,
	},
	{
		countryId,
		name: `Hipólito Yrigoyen`,
		tookOffice: new Date(`12 October 1916`),
		leftOffice: new Date(`12 October 1922`),
		party: `Radical Civic Union`,
		leaning: 0,
	},
	{
		countryId,
		name: `Marcelo Torcuato de Alvear`,
		tookOffice: new Date(`12 October 1922`),
		leftOffice: new Date(`12 October 1928`),
		party: `Radical Civic Union`,
		leaning: 0,
	},
	{
		countryId,
		name: `Hipólito Yrigoyen`,
		tookOffice: new Date(`12 October 1928`),
		leftOffice: new Date(`6 September 1930`),
		party: `Radical Civic Union`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Félix Uriburu`,
		tookOffice: new Date(`6 September 1930`),
		leftOffice: new Date(`20 February 1932`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Agustín Pedro Justo`,
		tookOffice: new Date(`20 February 1932`),
		leftOffice: new Date(`20 February 1938`),
		party: `Radical Civic Union (Concordancia)`,
		leaning: 0,
	},
	{
		countryId,
		name: `Roberto María Ortiz`,
		tookOffice: new Date(`20 February 1938`),
		leftOffice: new Date(`27 June 1942`),
		party: `Radical Civic Union (Concordancia)`,
		leaning: 0,
	},
	{
		countryId,
		name: `Ramón Castillo`,
		tookOffice: new Date(`27 June 1942`),
		leftOffice: new Date(`4 June 1943`),
		party: `National Democratic Party (Concordancia)`,
		leaning: 0,
	},
	{
		countryId,
		name: `Arturo Franklin Rawson`,
		tookOffice: new Date(`4 June 1943`),
		leftOffice: new Date(`7 June 1943`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Pedro Pablo Ramírez`,
		tookOffice: new Date(`7 June 1943`),
		leftOffice: new Date(`9 March 1944`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Edelmiro Julián Farrell`,
		tookOffice: new Date(`9 March 1944`),
		leftOffice: new Date(`4 June 1946`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Perón`,
		tookOffice: new Date(`4 June 1946`),
		leftOffice: new Date(`19 September 1955`),
		party: `Peronist`,
		leaning: 0,
	},
	{
		countryId,
		name: `Eduardo Lonardi`,
		tookOffice: new Date(`19 September 1955`),
		leftOffice: new Date(`13 November 1955`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},

	{
		countryId,
		name: `Pedro Eugenio Aramburu`,
		tookOffice: new Date(`13 November 1955`),
		leftOffice: new Date(`1 May 1958`),
		party: ``,
		leaning: 0,
	},
	{
		countryId,
		name: `Arturo Frondizi`,
		tookOffice: new Date(`1 May 1958`),
		leftOffice: new Date(`29 March 1962`),
		party: `Intransigent Radical Civic Union`,
		leaning: 0,
	},
	{
		countryId,
		name: `José María Guido`,
		tookOffice: new Date(`29 March 1962`),
		leftOffice: new Date(`12 October 1963`),
		party: `Intransigent Radical Civic Union`,
		leaning: 0,
	},
	{
		countryId,
		name: `Arturo Umberto Illia`,
		tookOffice: new Date(`12 October 1963`),
		leftOffice: new Date(`28 June 1966`),
		party: `Unión Cívica Radical del Pueblo`,
		leaning: 0,
	},
	{
		countryId,
		name: `Junta of Commanders of the Armed Forces - Pascual Pistarini, Benigno Ignacio Varela, Adolfo Teodoro Álvarez`,
		tookOffice: new Date(`28 June 1966`),
		leftOffice: new Date(`29 June 1966`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Carlos Onganía`,
		tookOffice: new Date(`29 June 1966`),
		leftOffice: new Date(`8 June 1970`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Junta of Commanders of the Armed Forces - Pedro Alberto José Gnavi, Alejandro Agustín Lanusse, Carlos Alberto Rey`,
		tookOffice: new Date(`8 June 1970`),
		leftOffice: new Date(`18 June 1970`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Roberto M. Levingston`,
		tookOffice: new Date(`18 June 1970`),
		leftOffice: new Date(`23 March 1971`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Junta of Commanders of the Armed Forces - Alejandro Agustín Lanusse, Pedro Alberto José Gnavi, Carlos Alberto Rey`,
		tookOffice: new Date(`23 March 1971`),
		leftOffice: new Date(`26 March 1971`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Alejandro Agustín Lanusse`,
		tookOffice: new Date(`26 March 1971`),
		leftOffice: new Date(`25 May 1973`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Héctor José Cámpora`,
		tookOffice: new Date(`25 May 1973`),
		leftOffice: new Date(`13 July 1973`),
		party: `Justicialist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Raúl Alberto Lastiri`,
		tookOffice: new Date(`13 July 1973`),
		leftOffice: new Date(`12 October 1973`),
		party: `Justicialist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Perón`,
		tookOffice: new Date(`12 October 1973`),
		leftOffice: new Date(`1 July 1974`),
		party: `Justicialist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Isabel Perón`,
		tookOffice: new Date(`29 June 1974`),
		leftOffice: new Date(`24 March 1976`),
		party: `Justicialist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Military Junta - Jorge Rafael Videla, Emilio Eduardo Massera, Orlando Ramón Agosti`,
		tookOffice: new Date(`24 March 1976`),
		leftOffice: new Date(`29 March 1976`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jorge Rafael Videla`,
		tookOffice: new Date(`29 March 1976`),
		leftOffice: new Date(`29 March 1981`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Roberto Eduardo Viola`,
		tookOffice: new Date(`29 March 1981`),
		leftOffice: new Date(`21 November 1981`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Horacio Tomás Liendo`,
		tookOffice: new Date(`21 November 1981`),
		leftOffice: new Date(`11 December 1981`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Lacoste`,
		tookOffice: new Date(`11 December 1981`),
		leftOffice: new Date(`22 December 1981`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Leopoldo Galtieri`,
		tookOffice: new Date(`22 December 1981`),
		leftOffice: new Date(`18 June 1982`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Alfredo Oscar Saint Jean`,
		tookOffice: new Date(`18 June 1982`),
		leftOffice: new Date(`1 July 1982`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Reynaldo Bignone`,
		tookOffice: new Date(`1 July 1982`),
		leftOffice: new Date(`10 December 1983`),
		party: `Argentine Armed Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Raúl Alfonsín`,
		tookOffice: new Date(`10 December 1983`),
		leftOffice: new Date(`8 July 1989`),
		party: `Radical Civic Union`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Saúl Menem Akil`,
		tookOffice: new Date(`8 July 1989`),
		leftOffice: new Date(`10 December 1999`),
		party: `Justicialist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Fernando de la Rúa`,
		tookOffice: new Date(`10 December 1999`),
		leftOffice: new Date(`20 December 2001`),
		party: `Radical Civic Union`,
		leaning: 0,
	},
	{
		countryId,
		name: `Ramón Puerta`,
		tookOffice: new Date(`20 December 2001`),
		leftOffice: new Date(`22 December 2001`),
		party: `Justicialist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Adolfo Rodríguez Saá`,
		tookOffice: new Date(`22 December 2001`),
		leftOffice: new Date(`30 December 2001`),
		party: `Justicialist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Eduardo Camaño`,
		tookOffice: new Date(`30 December 2001`),
		leftOffice: new Date(`2 January 2002`),
		party: `Justicialist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Eduardo Duhalde`,
		tookOffice: new Date(`2 January 2002`),
		leftOffice: new Date(`25 May 2003`),
		party: `Justicialist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Néstor Kirchner`,
		tookOffice: new Date(`25 May 2003`),
		leftOffice: new Date(`10 December 2007`),
		party: `Justicialist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Cristina Fernández de Kirchner`,
		tookOffice: new Date(`10 December 2007`),
		leftOffice: new Date(`10 December 2015`),
		party: `Justicialist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Mauricio Macri`,
		tookOffice: new Date(`10 December 2015`),
		leftOffice: new Date(`10 December 2019`),
		party: `Republican Proposal`,
		leaning: 0,
	},
	{
		countryId,
		name: `Alberto Fernández`,
		tookOffice: new Date(`10 December 2019`),
		leftOffice: new Date(),
		party: `Justicialist Party`,
		leaning: 0,
	},
];
