import { HeadOfStateNoId } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Bolivia`;

const countryId = 17;

export const bolivia: HeadOfStateNoId[] = [
	{
		countryId,
		name: `José Manuel Pando`,
		tookOffice: new Date(`25 October 1899`),
		leftOffice: new Date(`14 August 1904`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Ismael Montes`,
		tookOffice: new Date(`14 August 1904`),
		leftOffice: new Date(`12 August 1909`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Eliodoro Villazón`,
		tookOffice: new Date(`12 August 1909`),
		leftOffice: new Date(`14 August 1913`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Ismael Montes II`,
		tookOffice: new Date(`14 August 1913`),
		leftOffice: new Date(`15 August 1917`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Gutiérrez Guerra`,
		tookOffice: new Date(`15 August 1917`),
		leftOffice: new Date(`12 July 1920`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Military Junta - Bautista Saavedra, José María Escalier, José Manuel Ramírez`,
		tookOffice: new Date(`13 July 1920`),
		leftOffice: new Date(`16 July 1921`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Military Junta - Bautista Saavedra, José María Escalier, José Manuel Ramírez, Juan José Fernández`,
		tookOffice: new Date(`16 July 1920`),
		leftOffice: new Date(`28 January 1921`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Bautista Saavedra`,
		tookOffice: new Date(`28 January 1921`),
		leftOffice: new Date(`3 September 1925`),
		party: `Republican Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Felipe Segundo Guzmán`,
		tookOffice: new Date(`3 September 1925`),
		leftOffice: new Date(`10 January 1926`),
		party: `Republican Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Hernando Siles Reyes`,
		tookOffice: new Date(`10 January 1926`),
		leftOffice: new Date(`28 May 1930`),
		party: `Republican Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Council of Ministers`,
		tookOffice: new Date(`28 May 1930`),
		leftOffice: new Date(`28 June 1930`),
		party: ``,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Blanco Galindo`,
		tookOffice: new Date(`28 June 1930`),
		leftOffice: new Date(`5 March 1931`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Daniel Salamanca`,
		tookOffice: new Date(`5 March 1931`),
		leftOffice: new Date(`28 November 1934`),
		party: `Genuine Republican Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Luis Tejada Sorzano`,
		tookOffice: new Date(`28 November 1934`),
		leftOffice: new Date(`17 May 1936`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Germán Busch`,
		tookOffice: new Date(`17 May 1936`),
		leftOffice: new Date(`22 May 1936`),
		party: `Armed Forces of Bolivia - Socialist`,
		leaning: 0,
	},
	{
		countryId,
		name: `David Toro`,
		tookOffice: new Date(`22 May 1936`),
		leftOffice: new Date(`13 July 1937`),
		party: `Armed Forces of Bolivia - Socialist`,
		leaning: 0,
	},
	{
		countryId,
		name: `Germán Busch`,
		tookOffice: new Date(`13 July 1937`),
		leftOffice: new Date(`23 August 1939`),
		party: `Armed Forces of Bolivia - Socialist`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Quintanilla`,
		tookOffice: new Date(`23 August 1939`),
		leftOffice: new Date(`15 April 1940`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Enrique Peñaranda`,
		tookOffice: new Date(`15 April 1940`),
		leftOffice: new Date(`20 December 1943`),
		party: `Concordance Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Gualberto Villarroel`,
		tookOffice: new Date(`20 December 1943`),
		leftOffice: new Date(`21 July 1946`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Dámaso Arenas`,
		tookOffice: new Date(`21 July 1946`),
		leftOffice: new Date(`21 July 1946`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Néstor Guillén`,
		tookOffice: new Date(`21 July 1946`),
		leftOffice: new Date(`17 August 1946`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Tomás Monje`,
		tookOffice: new Date(`17 August 1946`),
		leftOffice: new Date(`10 March 1947`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Enrique Hertzog`,
		tookOffice: new Date(`10 March 1947`),
		leftOffice: new Date(`7 May 1949`),
		party: `Republican`,
		leaning: 0,
	},
	{
		countryId,
		name: `Mamerto Urriolagoitía`,
		tookOffice: new Date(`7 May 1949`),
		leftOffice: new Date(`16 May 1951`),
		party: `Socialist Unity`,
		leaning: 0,
	},
	{
		countryId,
		name: `Hugo Ballivián`,
		tookOffice: new Date(`16 May 1951`),
		leftOffice: new Date(`11 April 1952`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Hernán Siles Zuazo`,
		tookOffice: new Date(`11 April 1952`),
		leftOffice: new Date(`15 April 1952`),
		party: `Revolutionary Nationalist`,
		leaning: 0,
	},
	{
		countryId,
		name: `Víctor Paz Estenssoro I`,
		tookOffice: new Date(`15 April 1952`),
		leftOffice: new Date(`6 August 1956`),
		party: `Revolutionary Nationalist`,
		leaning: 0,
	},
	{
		countryId,
		name: `Hernán Siles Zuazo`,
		tookOffice: new Date(`6 August 1956`),
		leftOffice: new Date(`6 August 1960`),
		party: `Revolutionary Nationalist`,
		leaning: 0,
	},
	{
		countryId,
		name: `Víctor Paz Estenssoro II`,
		tookOffice: new Date(`6 August 1960`),
		leftOffice: new Date(`4 November 1964`),
		party: `Revolutionary Nationalist`,
		leaning: 0,
	},
	{
		countryId,
		name: `Military Junta - René Barrientos, Alfredo Ovando Candía, René Barrientos, Alfredo Ovando Candía`,
		tookOffice: new Date(`4 November 1964`),
		leftOffice: new Date(`5 November 1964`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `René Barrientos`,
		tookOffice: new Date(`5 November 1964`),
		leftOffice: new Date(`2 January 1966`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Alfredo Ovando Candía`,
		tookOffice: new Date(`2 January 1966`),
		leftOffice: new Date(`6 August 1966`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `René Barrientos`,
		tookOffice: new Date(`6 August 1966`),
		leftOffice: new Date(`27 April 1969`),
		party: `Armed Forces of Bolivia - Popular Christian`,
		leaning: 0,
	},
	{
		countryId,
		name: `Luis Adolfo Siles Salinas`,
		tookOffice: new Date(`27 April 1969`),
		leftOffice: new Date(`26 September 1969`),
		party: `Social Democratic`,
		leaning: 0,
	},
	{
		countryId,
		name: `Alfredo Ovando Candía`,
		tookOffice: new Date(`26 September 1969`),
		leftOffice: new Date(`6 October 1970`),
		party: `Armed Forces of Bolivia - Nationalist`,
		leaning: 0,
	},
	{
		countryId,
		name: `Rogelio Miranda`,
		tookOffice: new Date(`6 October 1970`),
		leftOffice: new Date(`6 October 1970`),
		party: `Armed Forces of Bolivia - Nationalist`,
		leaning: 0,
	},
	{
		countryId,
		name: `Military Junta - Efraín Guachalla, Alberto Albarracín, Fernando Sattori`,
		tookOffice: new Date(`6 October 1970`),
		leftOffice: new Date(`7 October 1970`),
		party: `Armed Forces of Bolivia - Nationalist`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan José Torres`,
		tookOffice: new Date(`7 October 1970`),
		leftOffice: new Date(`21 August 1971`),
		party: `Armed Forces of Bolivia - Nationalist`,
		leaning: 0,
	},
	{
		countryId,
		name: `Military Junta - Hugo Banzer, Andrés Selich Chop, Jaime Florentino Mendieta`,
		tookOffice: new Date(`21 August 1971`),
		leftOffice: new Date(`22 August 1971`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Hugo Banzer I`,
		tookOffice: new Date(`22 August 1971`),
		leftOffice: new Date(`20 July 1978`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Military Junta - Víctor González Fuentes, Gutenberg Barroso, Alfonso Villalpando`,
		tookOffice: new Date(`21 July 1978`),
		leftOffice: new Date(`21 July 1978`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Pereda`,
		tookOffice: new Date(`22 July 1978`),
		leftOffice: new Date(`24 November 1978`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `David Padilla`,
		tookOffice: new Date(`24 November 1978`),
		leftOffice: new Date(`8 August 1979`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Wálter Guevara`,
		tookOffice: new Date(`8 August 1979`),
		leftOffice: new Date(`1 November 1979`),
		party: `Authentic Revolutionary Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Alberto Natusch`,
		tookOffice: new Date(`1 November 1979`),
		leftOffice: new Date(`16 November 1979`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Lidia Gueiler`,
		tookOffice: new Date(`16 November 1979`),
		leftOffice: new Date(`17 July 1980`),
		party: `Revolutionary Party of the Nationalist Left`,
		leaning: 0,
	},
	{
		countryId,
		name: `Military Junta - Luis García Meza, Ramiro Terrazas Rodríguez, Waldo Bernal Pereira`,
		tookOffice: new Date(`17 July 1980`),
		leftOffice: new Date(`18 July 1980`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Luis García Meza`,
		tookOffice: new Date(`18 July 1980`),
		leftOffice: new Date(`4 August 1981`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Military Junta - Celso Torrelio, Óscar Pammo Rodríguez, Waldo Bernal Pereira`,
		tookOffice: new Date(`4 August 1981`),
		leftOffice: new Date(`4 September 1981`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Celso Torrelio`,
		tookOffice: new Date(`4 September 1981`),
		leftOffice: new Date(`19 July 1982`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Military Junta - Ángel Mariscal, Natalio Morales, Óscar Pammo Rodríguez`,
		tookOffice: new Date(`19 July 1981`),
		leftOffice: new Date(`21 July 1981`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Guido Vildoso`,
		tookOffice: new Date(`21 July 1982`),
		leftOffice: new Date(`10 October 1982`),
		party: `Armed Forces of Bolivia`,
		leaning: 0,
	},
	{
		countryId,
		name: `Hernán Siles Zuazo II`,
		tookOffice: new Date(`10 October 1982`),
		leftOffice: new Date(`6 August 1985`),
		party: `Leftwing Revolutionary Nationalist Movement`,
		leaning: 0,
	},
	{
		countryId,
		name: `Víctor Paz Estenssoro III`,
		tookOffice: new Date(`6 August 1985`),
		leftOffice: new Date(`6 August 1989`),
		party: `Revolutionary Nationalist Movement`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jaime Paz Zamora`,
		tookOffice: new Date(`6 August 1989`),
		leftOffice: new Date(`6 August 1993`),
		party: `Revolutionary Left Movement`,
		leaning: 0,
	},
	{
		countryId,
		name: `Gonzalo Sánchez de Lozada I`,
		tookOffice: new Date(`6 August 1993`),
		leftOffice: new Date(`6 August 1997`),
		party: `Revolutionary Nationalist Movement`,
		leaning: 0,
	},
	{
		countryId,
		name: `Hugo Banzer`,
		tookOffice: new Date(`6 August 1997`),
		leftOffice: new Date(`7 August 2001`),
		party: `Nationalist Democratic Action`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jorge Quiroga`,
		tookOffice: new Date(`7 August 2001`),
		leftOffice: new Date(`6 August 2002`),
		party: `Nationalist Democratic Action`,
		leaning: 0,
	},
	{
		countryId,
		name: `Gonzalo Sánchez de Lozada II`,
		tookOffice: new Date(`6 August 2002`),
		leftOffice: new Date(`17 October 2003`),
		party: `Revolutionary Nationalist Movement`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Diego Mesa Gisbert`,
		tookOffice: new Date(`17 October 2003`),
		leftOffice: new Date(`9 June 2005`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Eduardo Rodríguez Veltzé`,
		tookOffice: new Date(`9 June 2005`),
		leftOffice: new Date(`22 January 2006`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Evo Morales`,
		tookOffice: new Date(`22 January 2006`),
		leftOffice: new Date(`12 November 2019`),
		party: `Movement for Socialism`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jeanine Áñez`,
		tookOffice: new Date(`12 November 2019`),
		leftOffice: new Date(`8 November 2020`),
		party: `Social Democratic Movement`,
		leaning: 0,
	},
	{
		countryId,
		name: `Luis Arce`,
		tookOffice: new Date(`8 November 2020`),
		leftOffice: new Date(),
		party: `Movement for Socialism`,
		leaning: 0,
	},
];
