import { HeadOfStateNoId, leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Bolivia`;

const countryId = 17;

export const bolivia: HeadOfStateNoId[] = [
	{
		countryId,
		name: `José Manuel Pando`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`25 October 1899`),
		leftOffice: new Date(`14 August 1904`),
	},
	{
		countryId,
		name: `Ismael Montes`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`14 August 1904`),
		leftOffice: new Date(`12 August 1909`),
	},
	{
		countryId,
		name: `Eliodoro Villazón`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`12 August 1909`),
		leftOffice: new Date(`14 August 1913`),
	},
	{
		countryId,
		name: `Ismael Montes II`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`14 August 1913`),
		leftOffice: new Date(`15 August 1917`),
	},
	{
		countryId,
		name: `José Gutiérrez Guerra`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`15 August 1917`),
		leftOffice: new Date(`12 July 1920`),
	},
	{
		countryId,
		name: `Military Junta - Bautista Saavedra, José María Escalier, José Manuel Ramírez`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`13 July 1920`),
		leftOffice: new Date(`16 July 1921`),
	},
	{
		countryId,
		name: `Military Junta - Bautista Saavedra, José María Escalier, José Manuel Ramírez, Juan José Fernández`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`16 July 1920`),
		leftOffice: new Date(`28 January 1921`),
	},
	{
		countryId,
		name: `Bautista Saavedra`,
		party: `Republican Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`28 January 1921`),
		leftOffice: new Date(`3 September 1925`),
	},
	{
		countryId,
		name: `Felipe Segundo Guzmán`,
		party: `Republican Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`3 September 1925`),
		leftOffice: new Date(`10 January 1926`),
	},
	{
		countryId,
		name: `Hernando Siles Reyes`,
		party: `Republican Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`10 January 1926`),
		leftOffice: new Date(`28 May 1930`),
	},
	{
		countryId,
		name: `Council of Ministers`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`28 May 1930`),
		leftOffice: new Date(`28 June 1930`),
	},
	{
		countryId,
		name: `Carlos Blanco Galindo`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`28 June 1930`),
		leftOffice: new Date(`5 March 1931`),
	},
	{
		countryId,
		name: `Daniel Salamanca`,
		party: `Genuine Republican Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`5 March 1931`),
		leftOffice: new Date(`28 November 1934`),
	},
	{
		countryId,
		name: `José Luis Tejada Sorzano`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`28 November 1934`),
		leftOffice: new Date(`17 May 1936`),
	},
	{
		countryId,
		name: `Germán Busch`,
		party: `Armed Forces of Bolivia - Socialist`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`17 May 1936`),
		leftOffice: new Date(`22 May 1936`),
	},
	{
		countryId,
		name: `David Toro`,
		party: `Armed Forces of Bolivia - Socialist`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`22 May 1936`),
		leftOffice: new Date(`13 July 1937`),
	},
	{
		countryId,
		name: `Germán Busch`,
		party: `Armed Forces of Bolivia - Socialist`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`13 July 1937`),
		leftOffice: new Date(`23 August 1939`),
	},
	{
		countryId,
		name: `Carlos Quintanilla`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`23 August 1939`),
		leftOffice: new Date(`15 April 1940`),
	},
	{
		countryId,
		name: `Enrique Peñaranda`,
		party: `Concordance Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`15 April 1940`),
		leftOffice: new Date(`20 December 1943`),
	},
	{
		countryId,
		name: `Gualberto Villarroel`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`20 December 1943`),
		leftOffice: new Date(`21 July 1946`),
	},
	{
		countryId,
		name: `Dámaso Arenas`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`21 July 1946`),
		leftOffice: new Date(`21 July 1946`),
	},
	{
		countryId,
		name: `Néstor Guillén`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`21 July 1946`),
		leftOffice: new Date(`17 August 1946`),
	},
	{
		countryId,
		name: `Tomás Monje`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`17 August 1946`),
		leftOffice: new Date(`10 March 1947`),
	},
	{
		countryId,
		name: `Enrique Hertzog`,
		party: `Republican Socialist Unity Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`10 March 1947`),
		leftOffice: new Date(`7 May 1949`),
	},
	{
		countryId,
		name: `Mamerto Urriolagoitía`,
		party: `Republican Socialist Unity Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`7 May 1949`),
		leftOffice: new Date(`16 May 1951`),
	},
	{
		countryId,
		name: `Hugo Ballivián`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`16 May 1951`),
		leftOffice: new Date(`11 April 1952`),
	},
	{
		countryId,
		name: `Hernán Siles Zuazo`,
		party: `Revolutionary Nationalist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`11 April 1952`),
		leftOffice: new Date(`15 April 1952`),
	},
	{
		countryId,
		name: `Víctor Paz Estenssoro I`,
		party: `Revolutionary Nationalist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`15 April 1952`),
		leftOffice: new Date(`6 August 1956`),
	},
	{
		countryId,
		name: `Hernán Siles Zuazo`,
		party: `Revolutionary Nationalist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`6 August 1956`),
		leftOffice: new Date(`6 August 1960`),
	},
	{
		countryId,
		name: `Víctor Paz Estenssoro II`,
		party: `Revolutionary Nationalist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`6 August 1960`),
		leftOffice: new Date(`4 November 1964`),
	},
	{
		countryId,
		name: `Military Junta - René Barrientos, Alfredo Ovando Candía, René Barrientos, Alfredo Ovando Candía`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`4 November 1964`),
		leftOffice: new Date(`5 November 1964`),
	},
	{
		countryId,
		name: `René Barrientos`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`5 November 1964`),
		leftOffice: new Date(`2 January 1966`),
	},
	{
		countryId,
		name: `Alfredo Ovando Candía`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`2 January 1966`),
		leftOffice: new Date(`6 August 1966`),
	},
	{
		countryId,
		name: `René Barrientos`,
		party: `Armed Forces of Bolivia - Popular Christian`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`6 August 1966`),
		leftOffice: new Date(`27 April 1969`),
	},
	{
		countryId,
		name: `Luis Adolfo Siles Salinas`,
		party: `Social Democratic Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`27 April 1969`),
		leftOffice: new Date(`26 September 1969`),
	},
	{
		countryId,
		name: `Alfredo Ovando Candía`,
		party: `Armed Forces of Bolivia - Nationalist`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`26 September 1969`),
		leftOffice: new Date(`6 October 1970`),
	},
	{
		countryId,
		name: `Rogelio Miranda`,
		party: `Armed Forces of Bolivia - Nationalist`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`6 October 1970`),
		leftOffice: new Date(`6 October 1970`),
	},
	{
		countryId,
		name: `Military Junta - Efraín Guachalla, Alberto Albarracín, Fernando Sattori`,
		party: `Armed Forces of Bolivia - Nationalist`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`6 October 1970`),
		leftOffice: new Date(`7 October 1970`),
	},
	{
		countryId,
		name: `Juan José Torres`,
		party: `Armed Forces of Bolivia - Nationalist`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`7 October 1970`),
		leftOffice: new Date(`21 August 1971`),
	},
	{
		countryId,
		name: `Military Junta - Hugo Banzer, Andrés Selich Chop, Jaime Florentino Mendieta`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`21 August 1971`),
		leftOffice: new Date(`22 August 1971`),
	},
	{
		countryId,
		name: `Hugo Banzer I`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`22 August 1971`),
		leftOffice: new Date(`20 July 1978`),
	},
	{
		countryId,
		name: `Military Junta - Víctor González Fuentes, Gutenberg Barroso, Alfonso Villalpando`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`21 July 1978`),
		leftOffice: new Date(`21 July 1978`),
	},
	{
		countryId,
		name: `Juan Pereda`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`22 July 1978`),
		leftOffice: new Date(`24 November 1978`),
	},
	{
		countryId,
		name: `David Padilla`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`24 November 1978`),
		leftOffice: new Date(`8 August 1979`),
	},
	{
		countryId,
		name: `Wálter Guevara`,
		party: `Authentic Revolutionary Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`8 August 1979`),
		leftOffice: new Date(`1 November 1979`),
	},
	{
		countryId,
		name: `Alberto Natusch`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`1 November 1979`),
		leftOffice: new Date(`16 November 1979`),
	},
	{
		countryId,
		name: `Lidia Gueiler`,
		party: `Revolutionary Party of the Nationalist Left`,
		leaning: leanings.LEFT,
		tookOffice: new Date(`16 November 1979`),
		leftOffice: new Date(`17 July 1980`),
	},
	{
		countryId,
		name: `Military Junta - Luis García Meza, Ramiro Terrazas Rodríguez, Waldo Bernal Pereira`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`17 July 1980`),
		leftOffice: new Date(`18 July 1980`),
	},
	{
		countryId,
		name: `Luis García Meza`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`18 July 1980`),
		leftOffice: new Date(`4 August 1981`),
	},
	{
		countryId,
		name: `Military Junta - Celso Torrelio, Óscar Pammo Rodríguez, Waldo Bernal Pereira`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`4 August 1981`),
		leftOffice: new Date(`4 September 1981`),
	},
	{
		countryId,
		name: `Celso Torrelio`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`4 September 1981`),
		leftOffice: new Date(`19 July 1982`),
	},
	{
		countryId,
		name: `Military Junta - Ángel Mariscal, Natalio Morales, Óscar Pammo Rodríguez`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`19 July 1981`),
		leftOffice: new Date(`21 July 1981`),
	},
	{
		countryId,
		name: `Guido Vildoso`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`21 July 1982`),
		leftOffice: new Date(`10 October 1982`),
	},
	{
		countryId,
		name: `Hernán Siles Zuazo`,
		party: `Leftwing Revolutionary Nationalist Movement`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`10 October 1982`),
		leftOffice: new Date(`6 August 1985`),
	},
	{
		countryId,
		name: `Víctor Paz Estenssoro III`,
		party: `Revolutionary Nationalist Movement`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`6 August 1985`),
		leftOffice: new Date(`6 August 1989`),
	},
	{
		countryId,
		name: `Jaime Paz Zamora`,
		party: `Leftwing Revolutionary Nationalist Movement`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`6 August 1989`),
		leftOffice: new Date(`6 August 1993`),
	},
	{
		countryId,
		name: `Gonzalo Sánchez de Lozada I`,
		party: `Revolutionary Nationalist Movement`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`6 August 1993`),
		leftOffice: new Date(`6 August 1997`),
	},
	{
		countryId,
		name: `Hugo Banzer`,
		party: `Nationalist Democratic Action Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`6 August 1997`),
		leftOffice: new Date(`7 August 2001`),
	},
	{
		countryId,
		name: `Jorge Quiroga`,
		party: `Nationalist Democratic Action Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`7 August 2001`),
		leftOffice: new Date(`6 August 2002`),
	},
	{
		countryId,
		name: `Gonzalo Sánchez de Lozada II`,
		party: `Revolutionary Nationalist Movement`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`6 August 2002`),
		leftOffice: new Date(`17 October 2003`),
	},
	{
		countryId,
		name: `Carlos Diego Mesa Gisbert`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`17 October 2003`),
		leftOffice: new Date(`9 June 2005`),
	},
	{
		countryId,
		name: `Eduardo Rodríguez Veltzé`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`9 June 2005`),
		leftOffice: new Date(`22 January 2006`),
	},
	{
		countryId,
		name: `Evo Morales`,
		party: `Movement for Socialism`,
		leaning: leanings.FAR_LEFT,
		tookOffice: new Date(`22 January 2006`),
		leftOffice: new Date(`12 November 2019`),
	},
	{
		countryId,
		name: `Jeanine Áñez`,
		party: `Social Democratic Movement`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`12 November 2019`),
		leftOffice: new Date(`8 November 2020`),
	},
	{
		countryId,
		name: `Luis Arce`,
		party: `Movement for Socialism`,
		leaning: leanings.FAR_LEFT,
		tookOffice: new Date(`8 November 2020`),
		leftOffice: new Date(),
	},
];
