import { HeadOfStateNoId } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Chile`;

const countryId = 22;

export const chile: HeadOfStateNoId[] = [
	{
		countryId,
		name: `Bartolomé Blanche`,
		tookOffice: new Date(`13 September 1932`),
		leftOffice: new Date(`2 October 1932`),
		party: `Military of Chile`,
		leaning: 0,
	},
	{
		countryId,
		name: `Abraham Oyanedel`,
		tookOffice: new Date(`2 October 1932`),
		leftOffice: new Date(`24 December 1932`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Arturo Alessandri`,
		tookOffice: new Date(`24 December 1932`),
		leftOffice: new Date(`24 December 1938`),
		party: `Liberal Party of Chile`,
		leaning: 0,
	},
	{
		countryId,
		name: `Pedro Aguirre Cerda`,
		tookOffice: new Date(`24 December 1938`),
		leftOffice: new Date(`25 November 1941`),
		party: `Radical Party of Chile`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jerónimo Méndez`,
		tookOffice: new Date(`25 November 1941`),
		leftOffice: new Date(`2 April 1942`),
		party: `Radical Party of Chile`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Antonio Ríos`,
		tookOffice: new Date(`2 April 1942`),
		leftOffice: new Date(`27 June 1946`),
		party: `Radical Party of Chile`,
		leaning: 0,
	},
	{
		countryId,
		name: `Alfredo Duhalde`,
		tookOffice: new Date(`27 June 1946`),
		leftOffice: new Date(`3 August 1946`),
		party: `Radical Party of Chile`,
		leaning: 0,
	},
	{
		countryId,
		name: `Vicente Merino`,
		tookOffice: new Date(`3 August 1946`),
		leftOffice: new Date(`13 August 1946`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Alfredo Duhalde`,
		tookOffice: new Date(`13 August 1946`),
		leftOffice: new Date(`17 October 1946`),
		party: `Radical Party of Chile`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Antonio Iribarren`,
		tookOffice: new Date(`17 October 1946`),
		leftOffice: new Date(`3 November 1946`),
		party: `Radical Party of Chile`,
		leaning: 0,
	},
	{
		countryId,
		name: `Gabriel González Videla`,
		tookOffice: new Date(`3 November 1946`),
		leftOffice: new Date(`3 November 1952`),
		party: `Radical Party of Chile`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Ibáñez del Campo`,
		tookOffice: new Date(`3 November 1952`),
		leftOffice: new Date(`3 November 1958`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jorge Alessandri`,
		tookOffice: new Date(`3 November 1958`),
		leftOffice: new Date(`3 November 1964`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Eduardo Frei Montalva`,
		tookOffice: new Date(`3 November 1964`),
		leftOffice: new Date(`3 November 1970`),
		party: `Christian Democratic Party of Chile`,
		leaning: 0,
	},
	{
		countryId,
		name: `Salvador Allende`,
		tookOffice: new Date(`3 November 1970`),
		leftOffice: new Date(`11 September 1973`),
		party: `Socialist Party of Chile`,
		leaning: 0,
	},
	{
		countryId,
		name: `Augusto Pinochet`,
		tookOffice: new Date(`11 September 1973`),
		leftOffice: new Date(`17 June 1974`),
		party: ``,
		leaning: 0,
	},
	{
		countryId,
		name: `Patricio Aylwin`,
		tookOffice: new Date(`11 March 1990`),
		leftOffice: new Date(`11 March 1994`),
		party: `Christian Democratic Party of Chile`,
		leaning: 0,
	},
	{
		countryId,
		name: `Eduardo Frei Ruiz-Taglemall>`,
		tookOffice: new Date(`11 March 1994`),
		leftOffice: new Date(`11 March 2000`),
		party: `Christian Democratic Party of Chile`,
		leaning: 0,
	},
	{
		countryId,
		name: `Ricardo Lagosmall>`,
		tookOffice: new Date(`11 March 2000`),
		leftOffice: new Date(`11 March 2006`),
		party: `Party for Democracy (Chile)`,
		leaning: 0,
	},
	{
		countryId,
		name: `Michelle Bacheletmall>`,
		tookOffice: new Date(`11 March 2006`),
		leftOffice: new Date(`11 March 2010`),
		party: `Socialist Party of Chile`,
		leaning: 0,
	},
	{
		countryId,
		name: `Sebastián Piñeramall>`,
		tookOffice: new Date(`11 March 2010`),
		leftOffice: new Date(`11 March 2014`),
		party: `National Renewal (Chile)`,
		leaning: 0,
	},
	{
		countryId,
		name: `Michelle Bacheletmall>`,
		tookOffice: new Date(`11 March 2014`),
		leftOffice: new Date(`11 March 2018`),
		party: `Socialist Party of Chile`,
		leaning: 0,
	},
	{
		countryId,
		name: `Sebastián Piñeramall>`,
		tookOffice: new Date(`11 March 2018`),
		leftOffice: new Date(`11 March 2022`),
		party: `Chile Vamos`,
		leaning: 0,
	},
	{
		countryId,
		name: `Gabriel Boricmall>`,
		tookOffice: new Date(`11 March 2022`),
		leftOffice: new Date(),
		party: `Social Convergence`,
		leaning: 0,
	},
];
