import { HeadOfStateNoId, leanings } from '../../src/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-costa-rica/`;

const countryId = 8;

export const costaRica: HeadOfStateNoId[] = [
	{
		countryId,
		name: `Carlos Alvarado Quesada`,
		party: `Citizens’ Action Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`8 May 2018`),
		leftOffice: new Date(),
	},
	{
		countryId,
		name: `Luis Guillermo Solís`,
		party: `Citizens’ Action Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`8 May 2014`),
		leftOffice: new Date(`8 May 2018`),
	},
	{
		countryId,
		name: `Laura Chinchilla`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`8 May 2010`),
		leftOffice: new Date(`8 May 2014`),
	},
	{
		countryId,
		name: `Óscar Arias`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`8 May 2006`),
		leftOffice: new Date(`8 May 2010`),
	},
	{
		countryId,
		name: `Abel Pacheco de La Espriella`,
		party: `Social Christian Unity Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`8 May 2002`),
		leftOffice: new Date(`8 May 2006`),
	},
	{
		countryId,
		name: `Miguel Ángel Rodríguez`,
		party: `Social Christian Unity Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`8 May 1998`),
		leftOffice: new Date(`8 May 2002`),
	},
	{
		countryId,
		name: `José María Figueres Olsen`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`8 May 1994`),
		leftOffice: new Date(`8 May 1998`),
	},
	{
		countryId,
		name: `Rafael Ángel Calderón Fournier`,
		party: `Social Christian Unity Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`8 May 1990`),
		leftOffice: new Date(`8 May 1994`),
	},
	{
		countryId,
		name: `Óscar Arias`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`8 May 1986`),
		leftOffice: new Date(`8 May 1990`),
	},
	{
		countryId,
		name: `Luis Alberto Monge`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`8 May 1982`),
		leftOffice: new Date(`8 May 1986`),
	},
	{
		countryId,
		name: `Rodrigo Carazo Odio`,
		party: `Unity Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`8 May 1978`),
		leftOffice: new Date(`8 May 1982`),
	},
	{
		countryId,
		name: `Daniel Oduber Quirós`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`8 May 1974`),
		leftOffice: new Date(`8 May 1978`),
	},
	{
		countryId,
		name: `José Figueres Ferrer`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`8 May 1970`),
		leftOffice: new Date(`8 May 1974`),
	},
	{
		countryId,
		name: `Joaquín Trejos`,
		party: `National Unification Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`8 May 1966`),
		leftOffice: new Date(`8 May 1970`),
	},
	{
		countryId,
		name: `Francisco Orlich`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`8 May 1962`),
		leftOffice: new Date(`8 May 1966`),
	},
	{
		countryId,
		name: `Mario Echandi Jimenéz`,
		party: `National Unification Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`8 May 1958`),
		leftOffice: new Date(`8 May 1962`),
	},
	{
		countryId,
		name: `José Figueres Ferrer`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`8 May 1953`),
		leftOffice: new Date(`8 May 1958`),
	},
	{
		countryId,
		name: `Otilio Ulate Blanco`,
		party: `National Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`7 November 1949`),
		leftOffice: new Date(`8 May 1953`),
	},
	{
		countryId,
		name: `José Figueres Ferrer`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`8 May 1948`),
		leftOffice: new Date(`8 November 1949`),
	},
	{
		countryId,
		name: `Santos León Herrera`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`20 April 1948`),
		leftOffice: new Date(`8 May 1948`),
	},
	{
		countryId,
		name: `Teodoro Picado Michalski`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`8 May 1944`),
		leftOffice: new Date(`8 May 1948`),
	},
	{
		countryId,
		name: `Rafael Ángel Calderón`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`8 May 1940`),
		leftOffice: new Date(`8 May 1944`),
	},
	{
		countryId,
		name: `León Cortés Castro`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`8 May 1936`),
		leftOffice: new Date(`8 May 1940`),
	},
	{
		countryId,
		name: `Ricardo Jiménez Oreamuno`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`8 May 1932`),
		leftOffice: new Date(`8 May 1936`),
	},
	{
		countryId,
		name: `Cleto González Víquez`,
		party: `National Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`8 May 1928`),
		leftOffice: new Date(`8 May 1932`),
	},
	{
		countryId,
		name: `Ricardo Jiménez Oreamuno`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`8 May 1924`),
		leftOffice: new Date(`8 May 1928`),
	},
	{
		countryId,
		name: `Julio Acosta García`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`8 May 1920`),
		leftOffice: new Date(`8 May 1924`),
	},
	{
		countryId,
		name: `Francisco Aguilar Barquero`,
		party: `National Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`2 September 1919`),
		leftOffice: new Date(`8 May 1920`),
	},
	{
		countryId,
		name: `Juan Bautista Quirós Segura`,
		party: `Peliquista Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`13 August 1919`),
		leftOffice: new Date(`2 September 1919`),
	},
	{
		countryId,
		name: `Federico Tinoco Granados`,
		party: `Peliquista Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`27 January 1917`),
		leftOffice: new Date(`13 August 1919`),
	},
	{
		countryId,
		name: `Alfredo González`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`8 May 1914`),
		leftOffice: new Date(`27 January 1917`),
	},
	{
		countryId,
		name: `Ricardo Jiménez Oreamuno`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`8 May 1910`),
		leftOffice: new Date(`8 May 1914`),
	},
	{
		countryId,
		name: `Cleto González Víquez`,
		party: `National Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`8 May 1906`),
		leftOffice: new Date(`8 May 1910`),
	},
	{
		countryId,
		name: `Ascensión Esquivel Ibarra`,
		party: `National Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`8 May 1902`),
		leftOffice: new Date(`8 May 1906`),
	},
	{
		countryId,
		name: `Rafael Yglesias Castro`,
		party: `Civil Party`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`8 May 1894`),
		leftOffice: new Date(`8 May 1902`),
	},
	{
		countryId,
		name: `José Joaquín Rodríguez`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`8 May 1890`),
		leftOffice: new Date(`8 May 1894`),
	},
];
