import { HeadOfStateNoId, leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Cuba`;

const countryId = 24;

export const cuba: HeadOfStateNoId[] = [
	{
		countryId,
		name: `Tomás Estrada Palma`,
		party: `Republican Party of Havana`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`20 May 1902`),
		leftOffice: new Date(`28 September 1906`),
	},
	{
		countryId,
		name: `William H. Taft`,
		party: `United States Government`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`28 September 1906`),
		leftOffice: new Date(`13 October 1906`),
	},
	{
		countryId,
		name: `Charles Edward Magoon`,
		party: `United States Government`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`13 October 1906`),
		leftOffice: new Date(`28 January 1909`),
	},
	{
		countryId,
		name: `José Miguel Gómez`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`28 January 1909`),
		leftOffice: new Date(`20 May 1913`),
	},
	{
		countryId,
		name: `Mario García Menocal`,
		party: `National Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`20 May 1913`),
		leftOffice: new Date(`20 May 1921`),
	},
	{
		countryId,
		name: `Alfredo Zayas y Alfonso`,
		party: `National Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`20 May 1921`),
		leftOffice: new Date(`20 May 1925`),
	},
	{
		countryId,
		name: `Gerardo Machado`,
		party: `National Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`20 May 1925`),
		leftOffice: new Date(`12 August 1933`),
	},
	{
		countryId,
		name: `Alberto Herrera Franchi`,
		party: `Military`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`12 August 1933`),
		leftOffice: new Date(`13 August 1933`),
	},
	{
		countryId,
		name: `Carlos Manuel de Céspedes y Quesada`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`13 August 1933`),
		leftOffice: new Date(`5 September 1933`),
	},
	{
		countryId,
		name: `Pentarchy of 1933`,
		party: `Nonpartisan`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`5 September 1933`),
		leftOffice: new Date(`10 September 1933`),
	},
	{
		countryId,
		name: `Ramón Grau`,
		party: `Authentic Party`,
		leaning: leanings.LEFT,
		tookOffice: new Date(`10 September 1933`),
		leftOffice: new Date(`15 January 1934`),
	},
	{
		countryId,
		name: `Carlos Hevia`,
		party: `Authentic Party`,
		leaning: leanings.LEFT,
		tookOffice: new Date(`15 January 1934`),
		leftOffice: new Date(`18 January 1934`),
	},
	{
		countryId,
		name: `Manuel Márquez Sterling`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`18 January 1934`),
		leftOffice: new Date(`18 January 1934`),
	},
	{
		countryId,
		name: `Carlos Mendieta`,
		party: `National Union`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`18 January 1934`),
		leftOffice: new Date(`11 December 1935`),
	},
	{
		countryId,
		name: `José Agripino Barnet`,
		party: `National Union`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`11 December 1935`),
		leftOffice: new Date(`20 May 1936`),
	},
	{
		countryId,
		name: `Miguel Mariano Gómez`,
		party: `National Union`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`20 May 1936`),
		leftOffice: new Date(`24 December 1936`),
	},
	{
		countryId,
		name: `Federico Laredo Brú`,
		party: `National Union`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`24 December 1936`),
		leftOffice: new Date(`10 October 1940`),
	},
	{
		countryId,
		name: `Fulgencio Batista`,
		party: `Democratic Socialist Coalition`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`10 October 1940`),
		leftOffice: new Date(`10 October 1944`),
	},
	{
		countryId,
		name: `Ramón Grau`,
		party: `Authentic Party`,
		leaning: leanings.LEFT,
		tookOffice: new Date(`10 October 1944`),
		leftOffice: new Date(`10 October 1948`),
	},
	{
		countryId,
		name: `Carlos Prío Socarrás`,
		party: `Authentic Party`,
		leaning: leanings.LEFT,
		tookOffice: new Date(`10 October 1948`),
		leftOffice: new Date(`10 March 1952`),
	},
	{
		countryId,
		name: `Fulgencio Batista`,
		party: `Progressive Action Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`10 March 1952`),
		leftOffice: new Date(`14 August 1954`),
	},
	{
		countryId,
		name: `Andrés Domingo del Castillo`,
		party: `Progressive Action Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`14 August 1954`),
		leftOffice: new Date(`24 February 1955`),
	},
	{
		countryId,
		name: `Fulgencio Batista`,
		party: `Progressive Action Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`24 February 1955`),
		leftOffice: new Date(`1 January 1959`),
	},
	{
		countryId,
		name: `Anselmo Alliegro y Milá`,
		party: `Progressive Action Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`1 January 1959`),
		leftOffice: new Date(`2 January 1959`),
	},
	{
		countryId,
		name: `Carlos Manuel Piedra`,
		party: `Progressive Action Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`2 January 1959`),
		leftOffice: new Date(`3 January 1959`),
	},
	{
		countryId,
		name: `Manuel Urrutia Lleó`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`3 January 1959`),
		leftOffice: new Date(`18 July 1959`),
	},
	{
		countryId,
		name: `Osvaldo Dorticós Torrado`,
		party: `Socialist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: new Date(`18 July 1959`),
		leftOffice: new Date(`2 December 1976`),
	},
	{
		countryId,
		name: `Fidel Castro`,
		party: `Communist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: new Date(`2 December 1976`),
		leftOffice: new Date(`24 February 2008`),
	},
	{
		countryId,
		name: `Raúl Castro`,
		party: `Communist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: new Date(`24 February 2008`),
		leftOffice: new Date(`19 April 2018`),
	},
	{
		countryId,
		name: `Miguel Díaz-Canel`,
		party: `Communist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: new Date(`19 April 2018`),
		leftOffice: new Date(),
	},
];
