import { HeadOfStateNoId } from '../../src/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-of-ecuador/`;

const countryId = 12;

export const ecuador: HeadOfStateNoId[] = [
	{
		countryId,
		name: `Guillermo Lasso`,
		tookOffice: new Date(`24 May 2021`),
		leftOffice: new Date(),
		party: `Creating Opportunities`,
		leaning: 0,
	},
	{
		countryId,
		name: `Lenín Moreno`,
		tookOffice: new Date(`24 May 2017`),
		leftOffice: new Date(`24 May 2021`),
		party: `PAIS Alliance`,
		leaning: 0,
	},
	{
		countryId,
		name: `Rafael Correa`,
		tookOffice: new Date(`15 January 2007`),
		leftOffice: new Date(`24 May 2017`),
		party: `PAIS Alliance`,
		leaning: 0,
	},
	{
		countryId,
		name: `Alfredo Palacio`,
		tookOffice: new Date(`20 April 2005`),
		leftOffice: new Date(`15 January 2007`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Lucio Gutiérrez`,
		tookOffice: new Date(`15 January 2003`),
		leftOffice: new Date(`20 April 2005`),
		party: `Patriotic Society Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Gustavo Noboa`,
		tookOffice: new Date(`22 January 2000`),
		leftOffice: new Date(`January 15 2003`),
		party: `Popular Democracy`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jamil Mahuad`,
		tookOffice: new Date(`10 August 1998`),
		leftOffice: new Date(`21 January 2000`),
		party: `Popular Democracy`,
		leaning: 0,
	},
	{
		countryId,
		name: `Fabián Alarcón`,
		tookOffice: new Date(`11 February 1997`),
		leftOffice: new Date(`10 August 1998`),
		party: `Alfarista Radical Front`,
		leaning: 0,
	},
	{
		countryId,
		name: `Rosalía Arteaga`,
		tookOffice: new Date(`9 February 1997`),
		leftOffice: new Date(`11 February 1997`),
		party: `Alfarista Radical Front`,
		leaning: 0,
	},
	{
		countryId,
		name: `Fabián Alarcón`,
		tookOffice: new Date(`6 February 1997`),
		leftOffice: new Date(`9 February 1997`),
		party: `Alfarista Radical Front`,
		leaning: 0,
	},
	{
		countryId,
		name: `Abdalá Bucaram`,
		tookOffice: new Date(`10 August 1996`),
		leftOffice: new Date(`6 February 1997`),
		party: `Ecuadorian Roldosist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Sixto Durán-Ballén`,
		tookOffice: new Date(`10 August 1992`),
		leftOffice: new Date(`10 August 1996`),
		party: `Republican Union Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Rodrigo Borja`,
		tookOffice: new Date(`10 August 1988`),
		leftOffice: new Date(`10 August 1992`),
		party: `Party of the Democratic Left`,
		leaning: 0,
	},
	{
		countryId,
		name: `León Febres-Cordero`,
		tookOffice: new Date(`10 August 1984`),
		leftOffice: new Date(`10 August 1988`),
		party: `Social Christian Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Osvaldo Hurtado`,
		tookOffice: new Date(`24 May 1981`),
		leftOffice: new Date(`10 August 1984`),
		party: `Popular Democracy`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jaime Roldós Aguilera`,
		tookOffice: new Date(`10 August 1979`),
		leftOffice: new Date(`24 May 1981`),
		party: `Concentration of People’s Forces`,
		leaning: 0,
	},
	{
		countryId,
		name: `Supreme Government Council`,
		tookOffice: new Date(`11 January 1976`),
		leftOffice: new Date(`10 August 1979`),
		party: ``,
		leaning: 0,
	},
	{
		countryId,
		name: `Guillermo Rodríguez`,
		tookOffice: new Date(`15 February 1972`),
		leftOffice: new Date(`11 January 1976`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `José María Velasco Ibarra`,
		tookOffice: new Date(`1 September 1968`),
		leftOffice: new Date(`15 February 1972`),
		party: `Conservative`,
		leaning: 0,
	},
	{
		countryId,
		name: `Otto Arosemena`,
		tookOffice: new Date(`16 November 1966`),
		leftOffice: new Date(`31 August 1968`),
		party: `Democratic Institutionalist Coalition`,
		leaning: 0,
	},
	{
		countryId,
		name: `Clemente Yerovi`,
		tookOffice: new Date(`30 March 1966`),
		leftOffice: new Date(`16 November 1966`),
		party: ``,
		leaning: 0,
	},
	{
		countryId,
		name: `Military Junta`,
		tookOffice: new Date(`11 July 1963`),
		leftOffice: new Date(`29 March 1966`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Julio Arosemena Monroy`,
		tookOffice: new Date(`7 November 1961`),
		leftOffice: new Date(`11 July 1963`),
		party: `Radical Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `José María Velasco Ibarra`,
		tookOffice: new Date(`1 September 1960`),
		leftOffice: new Date(`7 November 1961`),
		party: `Conservative`,
		leaning: 0,
	},
	{
		countryId,
		name: `Camilo Ponce Enríquez`,
		tookOffice: new Date(`1 September 1956`),
		leftOffice: new Date(`1 September 1960`),
		party: `Partido Social Cristiano`,
		leaning: 0,
	},
	{
		countryId,
		name: `José María Velasco Ibarra`,
		tookOffice: new Date(`1 September 1952`),
		leftOffice: new Date(`1 September 1956`),
		party: `Conservative`,
		leaning: 0,
	},
	{
		countryId,
		name: `Galo Plaza`,
		tookOffice: new Date(`1 September 1948`),
		leftOffice: new Date(`1 September 1952`),
		party: `National Democratic Civic Movement`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Julio Arosemena Tola`,
		tookOffice: new Date(`17 September 1947`),
		leftOffice: new Date(`31 August 1948`),
		party: ``,
		leaning: 0,
	},
	{
		countryId,
		name: `Mariano Suárez`,
		tookOffice: new Date(`2 September 1947`),
		leftOffice: new Date(`17 September 1947`),
		party: ``,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Mancheno Cajas`,
		tookOffice: new Date(`23 August 1947`),
		leftOffice: new Date(`2 September 1947`),
		party: `Jéfe Supremo`,
		leaning: 0,
	},
	{
		countryId,
		name: `José María Velasco Ibarra`,
		tookOffice: new Date(`1 June 1944`),
		leftOffice: new Date(`23 August 1947`),
		party: `Conservative`,
		leaning: 0,
	},
	{
		countryId,
		name: `Julio Teodoro Salem`,
		tookOffice: new Date(`29 May 1944`),
		leftOffice: new Date(`31 May 1944`),
		party: `Liberal Radical Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Alberto Arroyo del Río`,
		tookOffice: new Date(`September 1,`),
		leftOffice: new Date(`May 28 1944`),
		party: `Ecuadorian Radical Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Julio Enrique Moreno`,
		tookOffice: new Date(`10 August 1940`),
		leftOffice: new Date(`31 August 1940`),
		party: ``,
		leaning: 0,
	},
	{
		countryId,
		name: `Andrés Córdova`,
		tookOffice: new Date(`11 December 1939`),
		leftOffice: new Date(`10 August 1940`),
		party: `Ecuadorian Radical Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Alberto Arroyo del Río`,
		tookOffice: new Date(`18 November 1939`),
		leftOffice: new Date(`10 December 1939`),
		party: `Ecuadorian Radical Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Aurelio Mosquera`,
		tookOffice: new Date(`2 December 1938`),
		leftOffice: new Date(`17 November 1939`),
		party: `Ecuadorian Radical Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Manuel María Borrero`,
		tookOffice: new Date(`10 August 1938`),
		leftOffice: new Date(`1 December 1938`),
		party: ``,
		leaning: 0,
	},
	{
		countryId,
		name: `Alberto Enríquez Gallo`,
		tookOffice: new Date(`23 October 1937`),
		leftOffice: new Date(`10 August 1938`),
		party: `Jéfe Supremo`,
		leaning: 0,
	},
	{
		countryId,
		name: `Federico Páez`,
		tookOffice: new Date(`26 September 1935`),
		leftOffice: new Date(`23 October 1937`),
		party: `Jéfe Supremo`,
		leaning: 0,
	},
	{
		countryId,
		name: `Antonio Pons`,
		tookOffice: new Date(`21 August 1935`),
		leftOffice: new Date(`25 September 1935`),
		party: ``,
		leaning: 0,
	},
	{
		countryId,
		name: `José María Velasco Ibarra`,
		tookOffice: new Date(`1 September 1934`),
		leftOffice: new Date(`21 August 1935`),
		party: `Conservative`,
		leaning: 0,
	},
];
