import { HeadOfStateNoId, leanings } from '../../src/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-el-salvador/`;

const countryId = 5;

export const elSalvador: HeadOfStateNoId[] = [
	{
		countryId,
		name: `Nayib Armando Bukele Ortez`,
		party: `Nuevas Ideas`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`1 June 2019`),
		leftOffice: new Date(),
	},
	{
		countryId,
		name: `Salvador Sánchez Cerén`,
		party: `Farabundo Martí National Liberation Front`,
		leaning: leanings.FAR_LEFT,
		tookOffice: new Date(`1 June 2014`),
		leftOffice: new Date(`1 June 2019`),
	},
	{
		countryId,
		name: `Mauricio Funes`,
		party: `Farabundo Martí National Liberation Front`,
		leaning: leanings.FAR_LEFT,
		tookOffice: new Date(`1 June 2009`),
		leftOffice: new Date(`1 June 2014`),
	},
	{
		countryId,
		name: `Antonio Saca`,
		party: `Nationalist Republican Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`1 June 2004`),
		leftOffice: new Date(`1 June 2009`),
	},
	{
		countryId,
		name: `Francisco Flores Pérez`,
		party: `Nationalist Republican Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`1 June 1999`),
		leftOffice: new Date(`1 June 2004`),
	},
	{
		countryId,
		name: `Armando Calderón Sol`,
		party: `Nationalist Republican Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`1 June 1994`),
		leftOffice: new Date(`1 June 1999`),
	},
	{
		countryId,
		name: `Alfredo Cristiani`,
		party: `Nationalist Republican Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`1 June 1989`),
		leftOffice: new Date(`1 June 1994`),
	},
	{
		countryId,
		name: `José Napoleón Duarte`,
		party: `Christian Democratic Party`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`1 June 1984`),
		leftOffice: new Date(`1 June 1989`),
	},
	{
		countryId,
		name: `Álvaro Magaña`,
		party: `Nationalist Republican Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`2 May 1982`),
		leftOffice: new Date(`1 June 1984`),
	},
	{
		countryId,
		name: `Revolutionary Government Junta`,
		party: `Armed Forces of El Salvador`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`15 October 1979`),
		leftOffice: new Date(`2 May 1982`),
	},
	{
		countryId,
		name: `Carlos Humberto Romero`,
		party: `Armed Forces of El Salvador / Party of National Conciliation`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`1 July 1977`),
		leftOffice: new Date(`15 October 1979`),
	},
	{
		countryId,
		name: `Arturo Armando Molina`,
		party: `Armed Forces of El Salvador / Party of National Conciliation`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`1 July 1972`),
		leftOffice: new Date(`1 July 1977`),
	},
	{
		countryId,
		name: `Fidel Sánchez Hernández`,
		party: `National Coalition Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`1 July 1967`),
		leftOffice: new Date(`1 July 1972`),
	},
	{
		countryId,
		name: `Julio Adalberto Rivera`,
		party: `National Coalition Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`1 July 1962`),
		leftOffice: new Date(`1 July 1967`),
	},
	{
		countryId,
		name: `Eusebio Rodolfo Cordón Cea`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`25 January 1962`),
		leftOffice: new Date(`1 July 1962`),
	},
	{
		countryId,
		name: `Civic-Military Directory`,
		party: `Civic-Military Directory`,
		leaning: 0,
		tookOffice: new Date(`25 January 1961`),
		leftOffice: new Date(`25 January 1962`),
	},
	{
		countryId,
		name: `Junta of Government`,
		party: `Junta of Government`,
		leaning: 0,
		tookOffice: new Date(`26 October 1960`),
		leftOffice: new Date(`25 January 1961`),
	},
	{
		countryId,
		name: `José María Lemus`,
		party: `Armed Forces of El Salvador / Revolutionary Party of Democratic Unification`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`14 September 1956`),
		leftOffice: new Date(`26 October 1960`),
	},
	{
		countryId,
		name: `Óscar Osorio`,
		party: `Armed Forces of El Salvador / Revolutionary Party of Democratic Unification`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`14 September 1950`),
		leftOffice: new Date(`14 September 1956`),
	},
	{
		countryId,
		name: `Revolutionary Council of Government`,
		party: `Revolutionary Council of Government`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`15 December 1948`),
		leftOffice: new Date(`14 September 1950`),
	},
	{
		countryId,
		name: `Salvador Castaneda Castro`,
		party: `Armed Forces of El Salvador / Unification Social Democratic Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`1 March 1945`),
		leftOffice: new Date(`14 December 1948`),
	},
	{
		countryId,
		name: `Osmín Aguirre y Salinas`,
		party: `Armed Forces of El Salvador`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`21 October 1944`),
		leftOffice: new Date(`1 March 1945`),
	},
	{
		countryId,
		name: `Andrés Ignacio Menéndez`,
		party: `Armed Forces of El Salvador / National Pro-Patria Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`9 May 1944`),
		leftOffice: new Date(`20 October 1944`),
	},
	{
		countryId,
		name: `Maximiliano Hernández Martínez`,
		party: `National Pro Patria Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`1 March 1935`),
		leftOffice: new Date(`9 May 1944`),
	},
	{
		countryId,
		name: `Andrés Ignacio Menéndez`,
		party: `Armed Forces of El Salvador/National Pro-Patria Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`29 August 1934`),
		leftOffice: new Date(`1 March 1935`),
	},
	{
		countryId,
		name: `Maximiliano Hernández Martínez`,
		party: `National Pro Patria Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`4 December 1931`),
		leftOffice: new Date(`28 August 1934`),
	},
	{
		countryId,
		name: `Arturo Araujo`,
		party: `Labor Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`1 March 1931`),
		leftOffice: new Date(`2 December 1931`),
	},
	{
		countryId,
		name: `Pío Romero Bosque`,
		party: `National Democratic Party`,
		leaning: 0,
		tookOffice: new Date(`1 March 1927`),
		leftOffice: new Date(`1 March 1931`),
	},
	{
		countryId,
		name: `Alfonso Quiñónez Molina`,
		party: `National Democratic Party`,
		leaning: 0,
		tookOffice: new Date(`1 March 1923`),
		leftOffice: new Date(`1 March 1927`),
	},
	{
		countryId,
		name: `Jorge Meléndez`,
		party: `National Democratic Party`,
		leaning: 0,
		tookOffice: new Date(`1 March 1919`),
		leftOffice: new Date(`1 March 1923`),
	},
	{
		countryId,
		name: `Alfonso Quiñónez Molina`,
		party: `National Democratic Party`,
		leaning: 0,
		tookOffice: new Date(`21 December 1918`),
		leftOffice: new Date(`1 March 1919`),
	},
	{
		countryId,
		name: `Carlos Meléndez`,
		party: `National Democratic Party`,
		leaning: 0,
		tookOffice: new Date(`1 March 1915`),
		leftOffice: new Date(`21 December 1918`),
	},
	{
		countryId,
		name: `Manuel Enrique Araujo`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`1 March 1911`),
		leftOffice: new Date(`8 February 1913`),
	},
	{
		countryId,
		name: `Fernando Figueroa`,
		party: `Armed Forces of El Salvador - Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: new Date(`1 March 1907`),
		leftOffice: new Date(`1 March 1911`),
	},
	{
		countryId,
		name: `Pedro José Escalón`,
		party: `Armed Forces of El Salvador - Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`1 March 1903`),
		leftOffice: new Date(`1 March 1907`),
	},
	{
		countryId,
		name: `Tomás Regalado`,
		party: `Armed Forces of El Salvador - Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: new Date(`14 November 1898`),
		leftOffice: new Date(`1 March 1903`),
	},
	{
		countryId,
		name: `Rafael Antonio Gutiérrez`,
		party: `Armed Forces of El Salvador - Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: new Date(`10 June 1894`),
		leftOffice: new Date(`13 November 1898`),
	},
	{
		countryId,
		name: `Carlos Basilio Ezeta y León`,
		party: `Armed Forces of El Salvador - Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: new Date(`22 June 1890`),
		leftOffice: new Date(`9 June 1894`),
	},
	{
		countryId,
		name: `Francisco Menéndez`,
		party: `Armed Forces of El Salvador - Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: new Date(`21 June 1885`),
		leftOffice: new Date(`22 June 1890`),
	},
	{
		countryId,
		name: `Rafael Zaldívar`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: new Date(`1 May 1876`),
		leftOffice: new Date(`21 June 1885`),
	},
	{
		countryId,
		name: `Andrés del Valle`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: new Date(`1 February 1876`),
		leftOffice: new Date(`1 May 1876`),
	},
];
