import { HeadOfStateNoId } from '../../src/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-el-salvador/`;

const countryId = 5;

export const elSalvador: HeadOfStateNoId[] = [
	{
		countryId,
		name: `Nayib Armando Bukele Ortez`,
		tookOffice: new Date(`1 June 2019`),
		leftOffice: new Date(),
		party: `Nuevas Ideas`,
		leaning: 0,
	},
	{
		countryId,
		name: `Salvador Sánchez Cerén`,
		tookOffice: new Date(`1 June 2014`),
		leftOffice: new Date(`1 June 2019`),
		party: `Farabundo Martí National Liberation Front`,
		leaning: 0,
	},
	{
		countryId,
		name: `Mauricio Funes`,
		tookOffice: new Date(`1 June 2009`),
		leftOffice: new Date(`1 June 2014`),
		party: `Farabundo Martí National Liberation Front`,
		leaning: 0,
	},
	{
		countryId,
		name: `Antonio Saca`,
		tookOffice: new Date(`1 June 2004`),
		leftOffice: new Date(`1 June 2009`),
		party: `Nationalist Republican Alliance`,
		leaning: 0,
	},
	{
		countryId,
		name: `Francisco Flores Pérez`,
		tookOffice: new Date(`1 June 1999`),
		leftOffice: new Date(`1 June 2004`),
		party: `Nationalist Republican Alliance`,
		leaning: 0,
	},
	{
		countryId,
		name: `Armando Calderón Sol`,
		tookOffice: new Date(`1 June 1994`),
		leftOffice: new Date(`1 June 1999`),
		party: `Nationalist Republican Alliance`,
		leaning: 0,
	},
	{
		countryId,
		name: `Alfredo Cristiani`,
		tookOffice: new Date(`1 June 1989`),
		leftOffice: new Date(`1 June 1994`),
		party: `Nationalist Republican Alliance`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Napoleón Duarte`,
		tookOffice: new Date(`1 June 1984`),
		leftOffice: new Date(`1 June 1989`),
		party: `Christian Democratic Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Álvaro Magaña`,
		tookOffice: new Date(`2 May 1982`),
		leftOffice: new Date(`1 June 1984`),
		party: `Nationalist Republican Alliance`,
		leaning: 0,
	},
	{
		countryId,
		name: `Revolutionary Government Junta`,
		tookOffice: new Date(`15 October 1979`),
		leftOffice: new Date(`2 May 1982`),
		party: `Military Dictatorship`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Humberto Romero`,
		tookOffice: new Date(`1 July 1977`),
		leftOffice: new Date(`15 October 1979`),
		party: `Military/Party of National Conciliation`,
		leaning: 0,
	},
	{
		countryId,
		name: `Arturo Armando Molina`,
		tookOffice: new Date(`1 July 1972`),
		leftOffice: new Date(`1 July 1977`),
		party: `Military/Party of National Conciliation`,
		leaning: 0,
	},
	{
		countryId,
		name: `Fidel Sánchez Hernández`,
		tookOffice: new Date(`1 July 1967`),
		leftOffice: new Date(`1 July 1972`),
		party: `National Coalition Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Julio Adalberto Rivera`,
		tookOffice: new Date(`1 July 1962`),
		leftOffice: new Date(`1 July 1967`),
		party: `National Coalition Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Eusebio Rodolfo Cordón Cea`,
		tookOffice: new Date(`25 January 1962`),
		leftOffice: new Date(`1 July 1962`),
		party: ``,
		leaning: 0,
	},
	{
		countryId,
		name: `Civic-Military Directory`,
		tookOffice: new Date(`25 January 1961`),
		leftOffice: new Date(`25 January 1962`),
		party: `Civic-Military Directory`,
		leaning: 0,
	},
	{
		countryId,
		name: `Junta of Government`,
		tookOffice: new Date(`26 October 1960`),
		leftOffice: new Date(`25 January 1961`),
		party: `Junta of Government`,
		leaning: 0,
	},
	{
		countryId,
		name: `José María Lemus`,
		tookOffice: new Date(`14 September 1956`),
		leftOffice: new Date(`26 October 1960`),
		party: `Military/Revolutionary Party of Democratic Unification`,
		leaning: 0,
	},
	{
		countryId,
		name: `Óscar Osorio`,
		tookOffice: new Date(`14 September 1950`),
		leftOffice: new Date(`14 September 1956`),
		party: `Military/Revolutionary Party of Democratic Unification`,
		leaning: 0,
	},
	{
		countryId,
		name: `Revolutionary Council of Government`,
		tookOffice: new Date(`15 December 1948`),
		leftOffice: new Date(`14 September 1950`),
		party: `Revolutionary Council of Government`,
		leaning: 0,
	},
	{
		countryId,
		name: `Salvador Castaneda Castro`,
		tookOffice: new Date(`1 March 1945`),
		leftOffice: new Date(`14 December 1948`),
		party: `Military/Unification Social Democratic Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Osmín Aguirre y Salinas`,
		tookOffice: new Date(`21 October 1944`),
		leftOffice: new Date(`1 March 1945`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Andrés Ignacio Menéndez`,
		tookOffice: new Date(`9 May 1944`),
		leftOffice: new Date(`20 October 1944`),
		party: `Military/National Pro-Patria Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Maximiliano Hernández Martínez`,
		tookOffice: new Date(`1 March 1935`),
		leftOffice: new Date(`9 May 1944`),
		party: `Partido Nacional ‘Pro-Patria’`,
		leaning: 0,
	},
	{
		countryId,
		name: `Andrés Ignacio Menéndez`,
		tookOffice: new Date(`29 August 1934`),
		leftOffice: new Date(`1 March 1935`),
		party: `Military/National Pro-Patria Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Maximiliano Hernández Martínez`,
		tookOffice: new Date(`4 December 1931`),
		leftOffice: new Date(`28 August 1934`),
		party: `Partido Nacional ‘Pro-Patria’`,
		leaning: 0,
	},
	{
		countryId,
		name: `Arturo Araujo`,
		tookOffice: new Date(`1 March 1931`),
		leftOffice: new Date(`2 December 1931`),
		party: `Labor Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Pío Romero Bosque`,
		tookOffice: new Date(`1 March 1927`),
		leftOffice: new Date(`1 March 1931`),
		party: `National Democratic Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Alfonso Quiñónez Molina`,
		tookOffice: new Date(`1 March 1923`),
		leftOffice: new Date(`1 March 1927`),
		party: `National Democratic Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jorge Meléndez`,
		tookOffice: new Date(`1 March 1919`),
		leftOffice: new Date(`1 March 1923`),
		party: `National Democratic Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Alfonso Quiñónez Molina`,
		tookOffice: new Date(`21 December 1918`),
		leftOffice: new Date(`1 March 1919`),
		party: `National Democratic Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Meléndez`,
		tookOffice: new Date(`1 March 1915`),
		leftOffice: new Date(`21 December 1918`),
		party: `National Democratic Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Manuel Enrique Araujo`,
		tookOffice: new Date(`1 March 1911`),
		leftOffice: new Date(`8 February 1913`),
		party: ``,
		leaning: 0,
	},
	{
		countryId,
		name: `Fernando Figueroa`,
		tookOffice: new Date(`1 March 1907`),
		leftOffice: new Date(`1 March 1911`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Pedro José Escalón`,
		tookOffice: new Date(`1 March 1903`),
		leftOffice: new Date(`1 March 1907`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Tomás Regalado`,
		tookOffice: new Date(`14 November 1898`),
		leftOffice: new Date(`1 March 1903`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Rafael Antonio Gutiérrez`,
		tookOffice: new Date(`10 June 1894`),
		leftOffice: new Date(`13 November 1898`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Ezeta`,
		tookOffice: new Date(`22 June 1890`),
		leftOffice: new Date(`9 June 1894`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Francisco Menéndez`,
		tookOffice: new Date(`21 June 1885`),
		leftOffice: new Date(`22 June 1890`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Rafael Zaldívar`,
		tookOffice: new Date(`1 May 1876`),
		leftOffice: new Date(`21 June 1885`),
		party: `Liberal`,
		leaning: 0,
	},
	{
		countryId,
		name: `Andrés del Valle`,
		tookOffice: new Date(`1 February 1876`),
		leftOffice: new Date(`1 May 1876`),
		party: `Liberal`,
		leaning: 0,
	},
];
