import { HeadOfStateNoId } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Haiti`;

const countryId = 26;

export const haiti: HeadOfStateNoId[] = [
	{
		countryId,
		name: `Toussaint Louverture`,
		tookOffice: new Date(`1 January 1791`),
		leftOffice: new Date(`6 May 1802`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `François Duvalier`,
		tookOffice: new Date(`22 October 1957`),
		leftOffice: new Date(`21 April 1971`),
		party: `National Unity Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jean-Claude Duvalier`,
		tookOffice: new Date(`21 April 1971`),
		leftOffice: new Date(`7 February 1986`),
		party: `National Unity Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Henri Namphy`,
		tookOffice: new Date(`7 February 1986`),
		leftOffice: new Date(`7 February 1988`),
		party: `Armed Forces of Haiti`,
		leaning: 0,
	},
	{
		countryId,
		name: `Leslie Manigat`,
		tookOffice: new Date(`7 February 1988`),
		leftOffice: new Date(`20 June 1988`),
		party: `Rally of Progressive National Democrats`,
		leaning: 0,
	},
	{
		countryId,
		name: `Henri Namphy`,
		tookOffice: new Date(`20 June 1988`),
		leftOffice: new Date(`17 September 1988`),
		party: `Armed Forces of Haiti`,
		leaning: 0,
	},
	{
		countryId,
		name: `Prosper Avril`,
		tookOffice: new Date(`17 September 1988`),
		leftOffice: new Date(`10 March 1990`),
		party: `Armed Forces of Haiti`,
		leaning: 0,
	},
	{
		countryId,
		name: `Hérard Abraham`,
		tookOffice: new Date(`10 March 1990`),
		leftOffice: new Date(`13 March 1990`),
		party: `Armed Forces of Haiti`,
		leaning: 0,
	},
	{
		countryId,
		name: `Ertha Pascal-Trouillot`,
		tookOffice: new Date(`13 March 1990`),
		leftOffice: new Date(`7 February 1991`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jean-Bertrand Aristide`,
		tookOffice: new Date(`7 February 1991`),
		leftOffice: new Date(`29 September 1991`),
		party: `Struggling People's Organization`,
		leaning: 0,
	},
	{
		countryId,
		name: `Raoul Cédras`,
		tookOffice: new Date(`29 September 1991`),
		leftOffice: new Date(`8 October 1991`),
		party: `Armed Forces of Haiti`,
		leaning: 0,
	},
	{
		countryId,
		name: `Joseph Nérette`,
		tookOffice: new Date(`8 October 1991`),
		leftOffice: new Date(`19 June 1992`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Council of Ministers & Prime Minister Marc Bazin`,
		tookOffice: new Date(`19 June 1992`),
		leftOffice: new Date(`15 June 1993`),
		party: `Movement for the Instauration of Democracy in Haiti`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jean-Bertrand Aristide`,
		tookOffice: new Date(`15 June 1993`),
		leftOffice: new Date(`12 May 1994`),
		party: `Struggling People's Organization`,
		leaning: 0,
	},
	{
		countryId,
		name: `Émile Jonassaint`,
		tookOffice: new Date(`12 May 1994`),
		leftOffice: new Date(`12 October 1994`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jean-Bertrand Aristide`,
		tookOffice: new Date(`12 October 1994`),
		leftOffice: new Date(`7 February 1996`),
		party: `Struggling People's Organization`,
		leaning: 0,
	},
	{
		countryId,
		name: `René Préval`,
		tookOffice: new Date(`7 February 1996`),
		leftOffice: new Date(`7 February 2001`),
		party: `Fanmi Lavalas`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jean-Bertrand Aristide`,
		tookOffice: new Date(`7 February 2001`),
		leftOffice: new Date(`29 February 2004`),
		party: `Fanmi Lavalas`,
		leaning: 0,
	},
	{
		countryId,
		name: `Boniface Alexandre`,
		tookOffice: new Date(`29 February 2004`),
		leftOffice: new Date(`14 May 2006`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `René Préval`,
		tookOffice: new Date(`14 May 2006`),
		leftOffice: new Date(`14 May 2011`),
		party: `Lespwa / Inite`,
		leaning: 0,
	},
	{
		countryId,
		name: `Michel Martelly`,
		tookOffice: new Date(`14 May 2011`),
		leftOffice: new Date(`7 February 2016`),
		party: `Repons Peyizan`,
		leaning: 0,
	},
	{
		countryId,
		name: `Council of Ministers & Prime Minister Evans Paul`,
		tookOffice: new Date(`7 February 2016`),
		leftOffice: new Date(`14 February 2016`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jocelerme Privert`,
		tookOffice: new Date(`14 February 2016`),
		leftOffice: new Date(`7 February 2017`),
		party: `Inite`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jovenel Moïse`,
		tookOffice: new Date(`7 February 2017`),
		leftOffice: new Date(`7 July 2021`),
		party: `Haitian Tèt Kale Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Council of Ministers & Prime Minister Claude Joseph`,
		tookOffice: new Date(`7 July 2021`),
		leftOffice: new Date(`20 July 2021`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Council of Ministers & Prime Minister Ariel Henry`,
		tookOffice: new Date(`20 July 2021`),
		leftOffice: new Date(),
		party: `Independent`,
		leaning: 0,
	},
];
