import { HeadOfStateNoId } from '../../src/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-honduras/`;

const countryId = 6;

export const honduras: HeadOfStateNoId[] = [
	{
		countryId,
		name: `Xiomara Castro`,
		tookOffice: new Date(`27 January 2022`),
		leftOffice: new Date(),
		party: `Liberty and Refoundation`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Orlando Hernández`,
		tookOffice: new Date(`27 January 2014`),
		leftOffice: new Date(`27 January 2022`),
		party: `National Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Pepe Lobo`,
		tookOffice: new Date(`27 January 2010`),
		leftOffice: new Date(`27 January 2014`),
		party: `National Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Roberto Micheletti`,
		tookOffice: new Date(`28 June 2009`),
		leftOffice: new Date(`27 January 2010`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Manuel Zelaya`,
		tookOffice: new Date(`27 January 2006`),
		leftOffice: new Date(`28 June 2009`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Ricardo Maduro`,
		tookOffice: new Date(`27 January 2002`),
		leftOffice: new Date(`27 January 2006`),
		party: `National Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Flores`,
		tookOffice: new Date(`27 January 1998`),
		leftOffice: new Date(`27 January 2002`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Roberto Reina`,
		tookOffice: new Date(`27 January 1994`),
		leftOffice: new Date(`27 January 1998`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Rafael Callejas`,
		tookOffice: new Date(`27 January 1990`),
		leftOffice: new Date(`27 January 1994`),
		party: `National Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Azcona`,
		tookOffice: new Date(`27 January 1986`),
		leftOffice: new Date(`27 January 1990`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Roberto Suazo Córdoba`,
		tookOffice: new Date(`27 January 1982`),
		leftOffice: new Date(`27 January 1986`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Policarpo Paz García`,
		tookOffice: new Date(`7 August 1978`),
		leftOffice: new Date(`27 January 1982`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Alberto Melgar`,
		tookOffice: new Date(`22 April 1975`),
		leftOffice: new Date(`7 August 1978`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Oswaldo López`,
		tookOffice: new Date(`4 December 1972`),
		leftOffice: new Date(`22 April 1975`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Ramón Ernesto Cruz`,
		tookOffice: new Date(`7 June 1971`),
		leftOffice: new Date(`4 December 1972`),
		party: `National Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Oswaldo López`,
		tookOffice: new Date(`3 October 1963`),
		leftOffice: new Date(`7 June 1971`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Ramon Villeda Morales`,
		tookOffice: new Date(`21 December 1957`),
		leftOffice: new Date(`3 October 1963`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Military Government Council`,
		tookOffice: new Date(`21 October 1956`),
		leftOffice: new Date(`21 December 1957`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Julio Lozano Díaz`,
		tookOffice: new Date(`5 December 1954`),
		leftOffice: new Date(`21 October 1956`),
		party: `National Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Manuel Gálvez`,
		tookOffice: new Date(`1 January 1949`),
		leftOffice: new Date(`5 December 1954`),
		party: `National Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Tiburcio Carías Andino`,
		tookOffice: new Date(`1 February 1933`),
		leftOffice: new Date(`1 January 1949`),
		party: `National Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Vicente Mejía Colindres`,
		tookOffice: new Date(`1 February 1929`),
		leftOffice: new Date(`1 February 1933`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Miguel Paz Barahona`,
		tookOffice: new Date(`1 February 1925`),
		leftOffice: new Date(`1 February 1929`),
		party: `National Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Vicente Tosta`,
		tookOffice: new Date(`30 April 1924`),
		leftOffice: new Date(`1 February 1925`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Tiburcio Carías Andino`,
		tookOffice: new Date(`27 April 1924`),
		leftOffice: new Date(`30 April 1924`),
		party: `National Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Francisco Bueso`,
		tookOffice: new Date(`10 March 1924`),
		leftOffice: new Date(`27 April 1924`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Rafael López Gutiérrez`,
		tookOffice: new Date(`1 February 1920`),
		leftOffice: new Date(`10 March 1924`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Francisco Bográn`,
		tookOffice: new Date(`5 October 1919`),
		leftOffice: new Date(`1 February 1920`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Vicente Mejía Colindres`,
		tookOffice: new Date(`16 September 1919`),
		leftOffice: new Date(`5 October 1919`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Salvador Aguirre`,
		tookOffice: new Date(`21 March 1913`),
		leftOffice: new Date(`9 September 1919`),
		party: `National Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Miguel R. Dávila`,
		tookOffice: new Date(`18 April 1907`),
		leftOffice: new Date(`28 March 1911`),
		party: `National Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Miguel Oquelí Bustillo`,
		tookOffice: new Date(`25 February 1907`),
		leftOffice: new Date(`18 April 1907`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Manuel Bonilla`,
		tookOffice: new Date(`1 February 1912`),
		leftOffice: new Date(`21 March 1913`),
		party: `National Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Ángel Arias Boquín`,
		tookOffice: new Date(`1 February 1903`),
		leftOffice: new Date(`13 April 1903`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Terencio Sierra`,
		tookOffice: new Date(`1 February 1899`),
		leftOffice: new Date(`1 February 1903`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Policarpo Bonilla`,
		tookOffice: new Date(`22 February 1894`),
		leftOffice: new Date(`1 February 1899`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Domingo Vásquez`,
		tookOffice: new Date(`7 August 1893`),
		leftOffice: new Date(`22 February 1894`),
		party: `Conservative Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Ponciano Leiva`,
		tookOffice: new Date(`30 November 1891`),
		leftOffice: new Date(`7 August 1893`),
		party: `Conservative Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Luis Bográn`,
		tookOffice: new Date(`30 November 1883`),
		leftOffice: new Date(`30 November 1891`),
		party: `Conservative Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Council of Ministers`,
		tookOffice: new Date(`19 October 1883`),
		leftOffice: new Date(`30 November 1883`),
		party: `Council of Ministers`,
		leaning: 0,
	},
	{
		countryId,
		name: `Marco Aurelio Soto`,
		tookOffice: new Date(`27 August 1876`),
		leftOffice: new Date(`19 October 1883`),
		party: `Liberal Party`,
		leaning: 0,
	},
];
