import { HeadOfStateNoId, leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Mexico`;

const countryId = 2;

export const mexico: HeadOfStateNoId[] = [
	{
		countryId,
		name: `Lázaro Cárdenas`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 December 1934`,
		leftOffice: `30 November 1940`,
	},
	{
		countryId,
		name: `Manuel Ávila Camacho`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 December 1940`,
		leftOffice: `30 November 1946`,
	},
	{
		countryId,
		name: `Miguel Alemán Valdés`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 December 1946`,
		leftOffice: `30 November 1952`,
	},
	{
		countryId,
		name: `Adolfo Ruiz Cortines`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 December 1952`,
		leftOffice: `30 November 1958`,
	},
	{
		countryId,
		name: `Adolfo López Mateos`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 December 1958`,
		leftOffice: `30 November 1964`,
	},
	{
		countryId,
		name: `Gustavo Díaz Ordaz`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 December 1964`,
		leftOffice: `30 November 1970`,
	},
	{
		countryId,
		name: `Luis Echeverría Álvarez`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 December 1970`,
		leftOffice: `30 November 1976`,
	},
	{
		countryId,
		name: `Lopez Portillo`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 December 1976`,
		leftOffice: `30 November 1982`,
	},
	{
		countryId,
		name: `Miguel de la Madrid`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 December 1982`,
		leftOffice: `30 November 1988`,
	},
	{
		countryId,
		name: `Carlos Salinas de Gortari`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 December 1988`,
		leftOffice: `30 November 1994`,
	},
	{
		countryId,
		name: `Ernesto Zedillo Ponce de Leon`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 December 1994`,
		leftOffice: `30 November 2000`,
	},
	{
		countryId,
		name: `Vicente Fox`,
		party: `National Action Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 2000`,
		leftOffice: `30 November 2006`,
	},
	{
		countryId,
		name: `Felipe Calderon`,
		party: `National Action Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 2006`,
		leftOffice: `30 November 2012`,
	},
	{
		countryId,
		name: `Enrique Pena Nieto`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 December 2012`,
		leftOffice: `30 November 2018`,
	},
	{
		countryId,
		name: `Andrés Manuel López Obrador`,
		party: `National Regeneration Movement`,
		leaning: leanings.LEFT,
		tookOffice: `1 December 2018`,
		leftOffice: ``,
	},
];
