import { HeadOfStateNoId } from '../../src/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-paraguay/`;

const countryId = 18;

export const paraguay: HeadOfStateNoId[] = [
	{
		countryId,
		name: `Mario Abdo Benítez`,
		tookOffice: new Date(`15 August 2018`),
		leftOffice: new Date(),
		party: `Colorado Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Horacio Cartes`,
		tookOffice: new Date(`15 August 2013`),
		leftOffice: new Date(`15 August 2018`),
		party: `Colorado Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Federico Franco`,
		tookOffice: new Date(`22 June 2012`),
		leftOffice: new Date(`15 August 2013`),
		party: `Authentic Radical Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Fernando Lugo`,
		tookOffice: new Date(`15 August 2008`),
		leftOffice: new Date(`22 June 2012`),
		party: `Patriotic Alliance for Change`,
		leaning: 0,
	},
	{
		countryId,
		name: `Nicanor Duarte`,
		tookOffice: new Date(`15 August 2003`),
		leftOffice: new Date(`14 August 2008`),
		party: `Colorado Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Luis Ángel González Macchi`,
		tookOffice: new Date(`28 March 1999`),
		leftOffice: new Date(`15 August 2003`),
		party: `Colorado Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Raúl Cubas Grau`,
		tookOffice: new Date(`15 August 1998`),
		leftOffice: new Date(`29 March 1999`),
		party: `Colorado Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Carlos Wasmosy`,
		tookOffice: new Date(`15 August 1993`),
		leftOffice: new Date(`14 August 1998`),
		party: `Colorado Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Andrés Rodríguez`,
		tookOffice: new Date(`3 February 1989`),
		leftOffice: new Date(`15 August 1993`),
		party: `Colorado Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Alfredo Stroessner`,
		tookOffice: new Date(`15 August 1954`),
		leftOffice: new Date(`3 February 1989`),
		party: `Colorado Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Tomás Romero Pereira`,
		tookOffice: new Date(`5 May 1954`),
		leftOffice: new Date(`15 August 1954`),
		party: `Colorado Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Federico Chaves Careaga`,
		tookOffice: new Date(`10 September 1949`),
		leftOffice: new Date(`5 May 1954`),
		party: `Colorado Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Felipe Molas López`,
		tookOffice: new Date(`27 February 1949`),
		leftOffice: new Date(`10 September 1949`),
		party: `Colorado Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Raimundo Rolón`,
		tookOffice: new Date(`30 January 1949`),
		leftOffice: new Date(`27 February 1949`),
		party: `Colorado Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Natalicio González`,
		tookOffice: new Date(`16 August 1948`),
		leftOffice: new Date(`30 January 1949`),
		party: `Colorado Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Manuel Frutos`,
		tookOffice: new Date(`16 June 1948`),
		leftOffice: new Date(`15 August 1948`),
		party: `Colorado Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Higinio Morínigo`,
		tookOffice: new Date(`7 September 1940`),
		leftOffice: new Date(`3 June 1948`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Félix Estigarribia`,
		tookOffice: new Date(`15 August 1939`),
		leftOffice: new Date(`7 September 1940`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Félix Paiva`,
		tookOffice: new Date(`15 August 1937`),
		leftOffice: new Date(`15 August 1939`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Rafael Franco Ojeda`,
		tookOffice: new Date(`17 February 1936`),
		leftOffice: new Date(`13 August 1937`),
		party: `Febrerista Revolutionary`,
		leaning: 0,
	},
	{
		countryId,
		name: `Eusebio Ayala`,
		tookOffice: new Date(`15 August 1932`),
		leftOffice: new Date(`17 February 1936`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Patricio Guggiari`,
		tookOffice: new Date(`15 August 1928`),
		leftOffice: new Date(`15 August 1932`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Eligio Ayala`,
		tookOffice: new Date(`15 August 1924`),
		leftOffice: new Date(`15 August 1928`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Luis Alberto Riart`,
		tookOffice: new Date(`17 March 1924`),
		leftOffice: new Date(`15 August 1924`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Eligio Ayala`,
		tookOffice: new Date(`12 April 1923`),
		leftOffice: new Date(`17 March 1924`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Eusebio Ayala`,
		tookOffice: new Date(`7 November 1921`),
		leftOffice: new Date(`12 April 1923`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Manuel Gondra`,
		tookOffice: new Date(`15 August 1920`),
		leftOffice: new Date(`7 November 1921`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Pedro Montero`,
		tookOffice: new Date(`6 June 1919`),
		leftOffice: new Date(`15 August 1920`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Manuel Franco`,
		tookOffice: new Date(`15 August 1916`),
		leftOffice: new Date(`5 June 1919`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Eduardo Schaerer`,
		tookOffice: new Date(`15 August 1912`),
		leftOffice: new Date(`15 August 1916`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Emiliano González Navero`,
		tookOffice: new Date(`8 July 1908`),
		leftOffice: new Date(`25 November 1910`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Pedro Peña`,
		tookOffice: new Date(`28 February 1911`),
		leftOffice: new Date(`22 March 1912`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Liberato Marcial Rojas`,
		tookOffice: new Date(`5 July 1911`),
		leftOffice: new Date(`28 February 1912`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Albino Jara`,
		tookOffice: new Date(`17 January 1911`),
		leftOffice: new Date(`5 July 1911`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Manuel Gondra`,
		tookOffice: new Date(`25 November 1910`),
		leftOffice: new Date(`17 January 1911`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Emiliano González Navero`,
		tookOffice: new Date(`4 July 1908`),
		leftOffice: new Date(`25 November 1910`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Benigno Ferreira`,
		tookOffice: new Date(`25 November 1906`),
		leftOffice: new Date(`4 July 1908`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Cecilio Báez`,
		tookOffice: new Date(`8 December 1905`),
		leftOffice: new Date(`25 November 1906`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Bautista Gaona`,
		tookOffice: new Date(`19 December 1904`),
		leftOffice: new Date(`9 December 1905`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Antonio Escurra`,
		tookOffice: new Date(`25 November 1902`),
		leftOffice: new Date(`19 December 1904`),
		party: `Colorado Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Andrés Héctor Carvallo`,
		tookOffice: new Date(`9 January 1902`),
		leftOffice: new Date(`25 November 1902`),
		party: `Colorado Party`,
		leaning: 0,
	},
];
