import { HeadOfStateNoId, leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Venezuela`;

const countryId = 11;

export const venezuela: HeadOfStateNoId[] = [
	{
		countryId,
		name: `Juan Guaidó`,
		party: `Popular Will Party / Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`23 January 2019`),
		leftOffice: new Date(),
	},
	{
		countryId,
		name: `Nicolás Maduro`,
		party: `United Socialist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: new Date(`5 March 2013`),
		leftOffice: new Date(`10 January 2019`),
	},
	{
		countryId,
		name: `Hugo Chávez`,
		party: `United Socialist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: new Date(`14 April 2002`),
		leftOffice: new Date(`5 March 2013`),
	},
	{
		countryId,
		name: `Diosdado Cabello`,
		party: `United Socialist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: new Date(`13 April 2002`),
		leftOffice: new Date(`14 April 2002`),
	},
	{
		countryId,
		name: `Pedro Carmona`,
		party: `Independent`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`12 April 2002`),
		leftOffice: new Date(`13 April 2002`),
	},
	{
		countryId,
		name: `Hugo Chávez`,
		party: `United Socialist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: new Date(`2 February 1999`),
		leftOffice: new Date(`12 April 2002`),
	},
	{
		countryId,
		name: `Rafael Caldera`,
		party: `National Convergence`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`2 February 1994`),
		leftOffice: new Date(`2 February 1999`),
	},
	{
		countryId,
		name: `Ramón José Velásquez`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`5 June 1993`),
		leftOffice: new Date(`2 February 1994`),
	},
	{
		countryId,
		name: `Octavio Lepage`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`21 May 1993`),
		leftOffice: new Date(`5 June 1993`),
	},
	{
		countryId,
		name: `Carlos Andrés Pérez`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`2 February 1989`),
		leftOffice: new Date(`20 May 1993`),
	},
	{
		countryId,
		name: `Jaime Lusinchi`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`2 February 1984`),
		leftOffice: new Date(`2 February 1989`),
	},
	{
		countryId,
		name: `Luis Herrera Campins`,
		party: `Copei`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`12 March 1979`),
		leftOffice: new Date(`2 February 1984`),
	},
	{
		countryId,
		name: `Carlos Andrés Pérez`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`12 March 1974`),
		leftOffice: new Date(`12 March 1979`),
	},
	{
		countryId,
		name: `Rafael Caldera`,
		party: `Copei`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`11 March 1969`),
		leftOffice: new Date(`12 March 1974`),
	},
	{
		countryId,
		name: `Raúl Leoni`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`13 March 1964`),
		leftOffice: new Date(`11 March 1969`),
	},
	{
		countryId,
		name: `Rómulo Betancourt`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`13 February 1959`),
		leftOffice: new Date(`13 March 1964`),
	},
	{
		countryId,
		name: `Edgar Sanabria`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`14 November 1958`),
		leftOffice: new Date(`13 February 1959`),
	},
	{
		countryId,
		name: `Wolfgang Larrazábal`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`23 January 1958`),
		leftOffice: new Date(`14 November 1958`),
	},
	{
		countryId,
		name: `Marcos Pérez Jiménez`,
		party: `Armed Forces of Venezuela`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`2 December 1952`),
		leftOffice: new Date(`23 January 1958`),
	},
	{
		countryId,
		name: `Germán Suárez Flamerich`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`27 November 1950`),
		leftOffice: new Date(`2 December 1952`),
	},
	{
		countryId,
		name: `Carlos Delgado Chalbaud`,
		party: `Armed Forces of Venezuela`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`24 November 1948`),
		leftOffice: new Date(`13 November 1950`),
	},
	{
		countryId,
		name: `Rómulo Gallegos`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`17 February 1948`),
		leftOffice: new Date(`24 November 1948`),
	},
	{
		countryId,
		name: `Rómulo Betancourt`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`19 October 1945`),
		leftOffice: new Date(`17 February 1948`),
	},
	{
		countryId,
		name: `Isaías Medina Angarita`,
		party: `Venezuelan Democratic Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: new Date(`5 May 1941`),
		leftOffice: new Date(`19 October 1945`),
	},
	{
		countryId,
		name: `Eleazar López Contreras`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`18 December 1935`),
		leftOffice: new Date(`5 May 1941`),
	},
	{
		countryId,
		name: `Juan Vicente Gómez`,
		party: `Armed Forces of Venezuela`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`13 June 1931`),
		leftOffice: new Date(`18 December 1935`),
	},
	{
		countryId,
		name: `Juan Bautista Pérez`,
		party: `Independent`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`30 May 1929`),
		leftOffice: new Date(`13 June 1931`),
	},
	{
		countryId,
		name: `Juan Vicente Gómez`,
		party: `Armed Forces of Venezuela`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`24 June 1922`),
		leftOffice: new Date(`30 May 1929`),
	},
	{
		countryId,
		name: `Victorino Márquez`,
		party: `Independent`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`19 April 1914`),
		leftOffice: new Date(`24 June 1922`),
	},
	{
		countryId,
		name: `José Gil Fortoul`,
		party: `Independent`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`5 August 1913`),
		leftOffice: new Date(`19 April 1914`),
	},
	{
		countryId,
		name: `Juan Vicente Gómez`,
		party: `Armed Forces of Venezuela`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`19 December 1908`),
		leftOffice: new Date(`5 August 1913`),
	},
	{
		countryId,
		name: `Cipriano Castro`,
		party: `Armed Forces of Venezuela`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: new Date(`20 October 1899`),
		leftOffice: new Date(`19 December 1908`),
	},
	{
		countryId,
		name: `Ignacio Andrade`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`28 February 1898`),
		leftOffice: new Date(`20 October 1899`),
	},
	{
		countryId,
		name: `Joaquín Crespo`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`7 October 1892`),
		leftOffice: new Date(`28 February 1898`),
	},
	{
		countryId,
		name: `Guillermo Tell Villegas Pulido`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`31 August 1892`),
		leftOffice: new Date(`7 October 1892`),
	},
	{
		countryId,
		name: `Guillermo Tell Villegas`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`17 June 1892`),
		leftOffice: new Date(`31 August 1892`),
	},
	{
		countryId,
		name: `Raimundo Andueza`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`19 March 1890`),
		leftOffice: new Date(`17 June 1892`),
	},
	{
		countryId,
		name: `Juan Pablo Rojas`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`2 July 1888`),
		leftOffice: new Date(`19 March 1890`),
	},
	{
		countryId,
		name: `Hermógenes López`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: new Date(`8 August 1887`),
		leftOffice: new Date(`2 July 1888`),
	},
	{
		countryId,
		name: `Antonio Guzmán Blanco`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`15 September 1886`),
		leftOffice: new Date(`8 August 1887`),
	},
	{
		countryId,
		name: `Joaquín Crespo`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`26 April 1884`),
		leftOffice: new Date(`15 September 1886`),
	},
	{
		countryId,
		name: `Antonio Guzmán Blanco`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`26 February 1879`),
		leftOffice: new Date(`26 April 1884`),
	},
	{
		countryId,
		name: `José Gregorio Valera`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`30 November 1878`),
		leftOffice: new Date(`26 February 1879`),
	},
	{
		countryId,
		name: `Francisco Linares Alcántara`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`27 February 1877`),
		leftOffice: new Date(`30 November 1878`),
	},
	{
		countryId,
		name: `Antonio Guzmán Blanco`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`27 April 1870`),
		leftOffice: new Date(`27 February 1877`),
	},
	{
		countryId,
		name: `Guillermo Tell Villegas`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`16 April 1870`),
		leftOffice: new Date(`27 April 1870`),
	},
	{
		countryId,
		name: `José Ruperto Monagas`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`20 February 1869`),
		leftOffice: new Date(`16 April 1870`),
	},
	{
		countryId,
		name: `Guillermo Tell Villegas`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`28 June 1868`),
		leftOffice: new Date(`20 February 1869`),
	},
	{
		countryId,
		name: `Manuel Ezequiel Bruzual`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`25 April 1868`),
		leftOffice: new Date(`28 June 1868`),
	},
	{
		countryId,
		name: `Juan Crisóstomo Falcón`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: new Date(`15 June 1863`),
		leftOffice: new Date(`25 April 1868`),
	},
	{
		countryId,
		name: `José Antonio Páez`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: new Date(`29 August 1861`),
		leftOffice: new Date(`15 June 1863`),
	},
];
