import { HeadOfStateNoId } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Venezuela`;

const countryId = 11;

export const venezuela: HeadOfStateNoId[] = [
	{
		countryId,
		name: `Juan Guaidó`,
		tookOffice: new Date(`23 January 2019`),
		leftOffice: new Date(),
		party: `Popular Will Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Nicolás Maduro`,
		tookOffice: new Date(`5 March 2013`),
		leftOffice: new Date(`10 January 2019`),
		party: `United Socialist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Hugo Chávez`,
		tookOffice: new Date(`14 April 2002`),
		leftOffice: new Date(`5 March 2013`),
		party: `United Socialist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Diosdado Cabello`,
		tookOffice: new Date(`13 April 2002`),
		leftOffice: new Date(`14 April 2002`),
		party: `Fifth Republic Movement`,
		leaning: 0,
	},
	{
		countryId,
		name: `Pedro Carmona`,
		tookOffice: new Date(`12 April 2002`),
		leftOffice: new Date(`13 April 2002`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Hugo Chávez`,
		tookOffice: new Date(`2 February 1999`),
		leftOffice: new Date(`12 April 2002`),
		party: `United Socialist Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Rafael Caldera`,
		tookOffice: new Date(`2 February 1994`),
		leftOffice: new Date(`2 February 1999`),
		party: `National Convergence`,
		leaning: 0,
	},
	{
		countryId,
		name: `Ramón José Velásquez`,
		tookOffice: new Date(`5 June 1993`),
		leftOffice: new Date(`2 February 1994`),
		party: `Democratic Action`,
		leaning: 0,
	},
	{
		countryId,
		name: `Octavio Lepage`,
		tookOffice: new Date(`21 May 1993`),
		leftOffice: new Date(`5 June 1993`),
		party: `Democratic Action`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Andrés Pérez`,
		tookOffice: new Date(`2 February 1989`),
		leftOffice: new Date(`20 May 1993`),
		party: `Democratic Action`,
		leaning: 0,
	},
	{
		countryId,
		name: `Jaime Lusinchi`,
		tookOffice: new Date(`2 February 1984`),
		leftOffice: new Date(`2 February 1989`),
		party: `Democratic Action`,
		leaning: 0,
	},
	{
		countryId,
		name: ` Luis Herrera Campins`,
		tookOffice: new Date(`12 March 1979`),
		leftOffice: new Date(`2 February 1984`),
		party: `Copei`,
		leaning: 0,
	},
	{
		countryId,
		name: ` Carlos Andrés Pérez`,
		tookOffice: new Date(`12 March 1974`),
		leftOffice: new Date(`12 March 1979`),
		party: `Democratic Action`,
		leaning: 0,
	},
	{
		countryId,
		name: ` Rafael Caldera`,
		tookOffice: new Date(`11 March 1969`),
		leftOffice: new Date(`12 March 1974`),
		party: `Copei`,
		leaning: 0,
	},
	{
		countryId,
		name: ` Raúl Leoni`,
		tookOffice: new Date(`13 March 1964`),
		leftOffice: new Date(`11 March 1969`),
		party: `Democratic Action`,
		leaning: 0,
	},
	{
		countryId,
		name: ` Rómulo Betancourt`,
		tookOffice: new Date(`February 13 13 1964`),
		leftOffice: new Date(`– March 13 1964`),
		party: `Democratic Action`,
		leaning: 0,
	},
	{
		countryId,
		name: ` Edgar Sanabria`,
		tookOffice: new Date(`14 November 1958`),
		leftOffice: new Date(`13 February 1959`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: ` Wolfgang Larrazábal`,
		tookOffice: new Date(`23 January 1958`),
		leftOffice: new Date(`14 November 1958`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Marcos Pérez Jiménez`,
		tookOffice: new Date(`2 December 1952`),
		leftOffice: new Date(`23 January 1958`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Germán Suárez Flamerich`,
		tookOffice: new Date(`27 November 1950`),
		leftOffice: new Date(`2 December 1952`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Carlos Delgado Chalbaud`,
		tookOffice: new Date(`24 November 1948`),
		leftOffice: new Date(`13 November 1950`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Rómulo Gallegos`,
		tookOffice: new Date(`17 February 1948`),
		leftOffice: new Date(`24 November 1948`),
		party: `Democratic Action`,
		leaning: 0,
	},
	{
		countryId,
		name: `Rómulo Betancourt`,
		tookOffice: new Date(`19 October 1945`),
		leftOffice: new Date(`17 February 1948`),
		party: `Democratic Action`,
		leaning: 0,
	},
	{
		countryId,
		name: `Isaías Medina Angarita`,
		tookOffice: new Date(`5 May 1941`),
		leftOffice: new Date(`19 October 1945`),
		party: `Venezuelan Democratic Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Eleazar López Contreras`,
		tookOffice: new Date(`18 December 1935`),
		leftOffice: new Date(`5 May 1941`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Vicente Gómez`,
		tookOffice: new Date(`13 June 1931`),
		leftOffice: new Date(`18 December 1935`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Bautista Pérez`,
		tookOffice: new Date(`30 May 1929`),
		leftOffice: new Date(`13 June 1931`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Vicente Gómez`,
		tookOffice: new Date(`24 June 1922`),
		leftOffice: new Date(`30 May 1929`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Victorino Márquez`,
		tookOffice: new Date(`19 April 1914`),
		leftOffice: new Date(`24 June 1922`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Gil Fortoul`,
		tookOffice: new Date(`5 August 1913`),
		leftOffice: new Date(`19 April 1914`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Vicente Gómez`,
		tookOffice: new Date(`19 December 1908`),
		leftOffice: new Date(`5 August 1913`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Cipriano Castro`,
		tookOffice: new Date(`20 October 1899`),
		leftOffice: new Date(`19 December 1908`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Ignacio Andrade`,
		tookOffice: new Date(`28 February 1898`),
		leftOffice: new Date(`20 October 1899`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Joaquín Crespo`,
		tookOffice: new Date(`7 October 1892`),
		leftOffice: new Date(`28 February 1898`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Guillermo Tell Villegas Pulido`,
		tookOffice: new Date(`31 August 1892`),
		leftOffice: new Date(`7 October 1892`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Guillermo Tell Villegas`,
		tookOffice: new Date(`17 June 1892`),
		leftOffice: new Date(`31 August 1892`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Raimundo Andueza`,
		tookOffice: new Date(`19 March 1890`),
		leftOffice: new Date(`17 June 1892`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Pablo Rojas`,
		tookOffice: new Date(`2 July 1888`),
		leftOffice: new Date(`19 March 1890`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Hermógenes López`,
		tookOffice: new Date(`8 August 1887`),
		leftOffice: new Date(`2 July 1888`),
		party: `Independent`,
		leaning: 0,
	},
	{
		countryId,
		name: `Antonio Guzmán Blanco`,
		tookOffice: new Date(`15 September 1886`),
		leftOffice: new Date(`8 August 1887`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Joaquín Crespo`,
		tookOffice: new Date(`26 April 1884`),
		leftOffice: new Date(`15 September 1886`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Antonio Guzmán Blanco`,
		tookOffice: new Date(`26 February 1879`),
		leftOffice: new Date(`26 April 1884`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Gregorio Valera`,
		tookOffice: new Date(`30 November 1878`),
		leftOffice: new Date(`26 February 1879`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Francisco Linares Alcántara`,
		tookOffice: new Date(`27 February 1877`),
		leftOffice: new Date(`30 November 1878`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Antonio Guzmán Blanco`,
		tookOffice: new Date(`27 April 1870`),
		leftOffice: new Date(`27 February 1877`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Guillermo Tell Villegas`,
		tookOffice: new Date(`16 April 1870`),
		leftOffice: new Date(`27 April 1870`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Ruperto Monagas`,
		tookOffice: new Date(`20 February 1869`),
		leftOffice: new Date(`16 April 1870`),
		party: `Military`,
		leaning: 0,
	},
	{
		countryId,
		name: `Guillermo Tell Villegas`,
		tookOffice: new Date(`28 June 1868`),
		leftOffice: new Date(`20 February 1869`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Manuel Ezequiel Bruzual`,
		tookOffice: new Date(`25 April 1868`),
		leftOffice: new Date(`28 June 1868`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `Juan Crisóstomo Falcón`,
		tookOffice: new Date(`15 June 1863`),
		leftOffice: new Date(`25 April 1868`),
		party: `Liberal Party`,
		leaning: 0,
	},
	{
		countryId,
		name: `José Antonio Páez`,
		tookOffice: new Date(`29 August 1861`),
		leftOffice: new Date(`15 June 1863`),
		party: `Military`,
		leaning: 0,
	},
];
